glotaran/pyglotaran

.jupyter_config.py, Vagrantfile, open_vagrant-jupyter.html, setup.py, ubuntu-bootstrap.sh
This PR concerns the issues #74 and  #73.
I updated the Vagrantfile to use ubuntu 18.04 LTS and use jupyterlab instead of notebooks.
I also removed some redundant package installations in ubuntu-bootstrap.sh and moved the installation of lmfit-varpro to setup.py (one step closer to a PYPI package).
For jupyterlab on vagrant not to conflict with possible running jupyter instances of users with default config, I can changed port 8888 to 9999 (over 9000 :P ) and removed the authetication token.
Thus a user now can just run "vagrant up" and click on "open_vagrant-jupyter.html" to get to jupyterlab or get a list with possible reasons why he/she isn't redirected.
Feel free to pretty up "open_vagrant-jupyter.html" with some css.
=> make using vagrant and jupyterlab easy

docs/installation.rst, setup.py
Following this [stackowerflow question](https://stackoverflow.com/questions/12518499/pip-ignores-dependency-links-in-setup-py#13587734) I added a version to the lmfit-varpro dependency and dependency_link, which makes it possible to install glotaran by running:
``pip install git+https://github.com/glotaran/glotaran.git@develop --process-dependency-links``
I tested it with this branch, [see](https://github.com/s-weigand/quickstart).
=> Make pip+git install possible

readthedocs.yml
Added a  [``readthedocs.yml``](https://docs.readthedocs.io/en/latest/yaml-config.html) so readthedocs uses python 3.6 to build the documentation.
closes #107
=> added readthedocs.yml, so python 3.6 will be used for building the docs

.travis.yml, requirements_dev.txt
* added ``pluggy>=0.7`` (needed for pytest) to `requirements_dev.txt`
* Made dev requirements installation on travis update requirements
This should fix the problems with travis
=> Fix failing travis builds #42 and #43

.travis.yml
Changed deprecated 'py37-dev' test to current python 3.7, for travis tests on linux.
**Note:**  flake8 will fail see #164 
closes #165
=> change py37-dev to current python 3.7 for travis tests on linux

.gitignore, .travis.yml, README.md, docs/source/installation.rst, requirements_dev.txt
Due to the renaming of `glotaran/glotaran` to `glotaran/pyglotaran` there have been multiple issues with broken links and the old encryped deployment password for travis-ci.
- fixed broken links in the docs and readme 
- updated deployment password on travis-ci
- changed bumpversion to [bump2version](https://github.com/c4urself/bump2version), which is the still maintained fork of bumpversion and also works with python 3
closes #213 
P.S.: The tests were broken before, which is obvious since I didn't change code. 😅
=> fix broken links and updated deployment password

setup.py
Changed meta information which are displayed on PyPi and named the link to http://glotaran.org '' GloTarAn Ecosystem
closes #223
=> Change meta information for PyPi

.github/workflows/CI_CD_actions.yml, README.md
This PR switches the CI/CD from travis-ci.org and appveyor.org, to [GitHub Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions).
Tests still fail, due to a [flake8 issue](https://github.com/s-weigand/glotaran/runs/303356941) and [an also locally broken test](https://github.com/s-weigand/glotaran/runs/303376399). With those 2 issues fixed, `pyglotaran` managed to [pass the test suite](https://github.com/s-weigand/glotaran/commit/2539bf867785d7c5e5196a44f5f6973699236af9/checks?check_suite_id=311387898).
Sadly for the moment we will lose some convenience services:
- **coveralls**: Atm the normal clients don't support actions and the action doesn't support the coverage output of `pytest-cov` ([see](https://github.com/coverallsapp/github-action/issues/15)). …
=> use gh actions for testing

.github/workflows/CI_CD_actions.yml
Give a brief summary of the changes.
- Rename gh actions from `Python package` to `Tests`
- Make the also trigger at PRs not only pushes
=> Fix small gh action errors

.github/workflows/CI_CD_actions.yml, README.md, setup.py
Coveralls doesn't support github actions  for none javascript projects yet, so my proposal is to use codecov.
This PR exchanges coveralls.io with codecov.io and also removes `netCDF` upperboundry as @joernweissenborn wanted.
=> Use codecov instead of coveralls

glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_matrix.py, glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py
Small bugfix
irf was none when running test_spectral_irf.py ... the test would pass but the entire kinetic trace would remain zero, this fixes that and tests still pass
cherry-picked commits from fix_kinetic_spectrum_matrix_irf branch from master to 'rebase' without divergence
=> Fix kinetic spectrum matrix irf2

.github/workflows/CI_CD_actions.yml
- `continue-on-error` was deprecated
- `token` isn't needed anymore for public repos and dropping it allows codcov upload from fork PRs
=> Adapted to changes in codecov action

readthedocs.yml, requirements_dev.txt, setup.py
This fixes the failing build of the docs on RTD.
Changes:
- Set minimum requirement of `setuptools>=41.2`, which is needed by `xarray`
- Made `setuptools` a pinned version in `requirements_dev.txt` since it is a peerdependency of xarray and a dependency of `pyglotaran`. This fixed version should not be updated by `dependabot`
- Updated ` readthedocs.yml` to version 2 style
closes #354
=> Fix doc dependencies

.github/workflows/CI_CD_actions.yml
Added 'Linkcheck summary' step to CI job 'docs-links', which only shows linkcheck related output.
**Testing**
closes #357
=> [CI] Add linkcheck summary

docs/source/conf.py, requirements_dev.txt
Deprecated `sphinx-autodoc-typehints` and use intrinsic typehint support of `sphinx>=3.0.0`.
I checked the output and it is the same, but the deprecation warning are gone (build log is about 1600 lines shorter).
**Testing**
closes #359
=> Use sphinx >= 3.0 for the docs

glotaran/analysis/test/test_optimization.py
This fixes some failing optimization test due to a change in lmfit 1.0.1,
where the argument ``max_nfev`` was changed slightly with the intention to
uniformly specify the maximum number of function evalutions (see their PR 610),
this effectively reduces the number of iteration that were run resulting in
a failure to converge within the fixed number of iterations.
Brief summary of the changes:
Increased nfev from 5 to 10 to allow for more iteration to get convergence.
Closes #397
=> Update test_optimization.py to fix #397

.github/workflows/autoupdate-pre-commit-config.yml, .pre-commit-config.yaml
This adds a workflow which runs `pre-commit autoupdate` on schedule or manually triggered with `workflow_dispatch`, and makes a PR if there are new versions of tool.
@jsnel In order for this to trigger the CI at PR's you need [create an access token](https://github.com/technote-space/create-pr-action#github_token) and add it as secret `ACTION_TRIGGER_TOKEN` to the repo.
=> Add pre-commit autoupdate workflow

glotaran/analysis/simulation.py, glotaran/builtin/models/kinetic_image/__init__.py, glotaran/builtin/models/kinetic_image/kinetic_image_result.py, glotaran/builtin/models/kinetic_spectrum/__init__.py, glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py, glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_result.py, glotaran/builtin/models/kinetic_spectrum/spectral_constraints.py, glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py, glotaran/builtin/models/kinetic_spectrum/spectral_relations.py, glotaran/model/attribute.py
This PR fixes all 'not valid as a type' type errors mypy trows and makes some module member exports more pythonic.
It reduces the type checking errors from [199](https://github.com/glotaran/pyglotaran/pull/444/checks?check_run_id=1458384107) to [183](https://github.com/s-weigand/pyglotaran/runs/1459302847?check_suite_focus=true).
In some cases `any` (builtin function) was used as type of index so I replaced them with of `typing.Any`.
But I think it should be `int` or `Union[int, float]`.
Also since the implementation of the interval checking is always the same it can be refactored to a helper function.
And
```python
def applies(interval):
return interval[0] <= index <= interval[1]
```
should be 
```python
def applies(interval):
return min(interval) <= index <= max(interval)
```
or there …
=> Fix 'not valid as a type' type checking errors

glotaran/analysis/test/test_optimization.py
Fix relative import to absolute import for convenience and consistency
In test_optimization run dask in single threaded mode. 
At least under Windows 10 with python 3.8.6 it's unusably slow otherwise.
**Testing**
Passed all tests, and much faster too. ^^
closes #458
=> Run test_optimization in single-threaded dask mode

requirements_dev.txt, setup.py
Removed leftover dask artifacts in dependencies since dask isn't part of glotaran since merging #455
=> Remove leftover dask artifacts

.pre-commit-config.yaml, glotaran/builtin/models/kinetic_image/initial_concentration.pyi, glotaran/builtin/models/kinetic_image/irf.pyi, glotaran/builtin/models/kinetic_image/k_matrix.pyi, glotaran/builtin/models/kinetic_image/kinetic_image_dataset_descriptor.pyi, glotaran/builtin/models/kinetic_image/kinetic_image_megacomplex.pyi, glotaran/builtin/models/kinetic_image/kinetic_image_model.pyi, glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_dataset_descriptor.pyi, glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py, glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.pyi, glotaran/builtin/models/kinetic_spectrum/spectral_constraints.pyi, glotaran/builtin/models/kinetic_spectrum/spectral_irf.pyi, glotaran/builtin/models/kinetic_spectrum/spectral_penalties.pyi, glotaran/builtin/models/kinetic_spectrum/spectral_relations.pyi, glotaran/builtin/models/kinetic_spectrum/spectral_shape.pyi, glotaran/model/base_model.pyi, glotaran/model/dataset_descriptor.pyi, pyproject.toml, requirements_dev.txt
Due to the [known limitations of mypy](https://github.com/python/mypy/wiki/Unsupported-Python-Features) we need type stub files for the runtime patched objects (Models and Modelattributes) so we get proper type checking.
Those files get ignored by the python runtime and are only evaluated when type checking.
This PR reduces the current typing errors from [183](https://github.com/glotaran/pyglotaran/pull/444/checks?check_run_id=1462988697) to [76](https://github.com/s-weigand/pyglotaran/runs/1476219358?check_suite_focus=true).
=> Add stubs for runtime patched objects

.pre-commit-config.yaml, glotaran/analysis/optimize.py, glotaran/analysis/problem.py, glotaran/analysis/result.py, glotaran/analysis/scheme.py, glotaran/analysis/test/test_optimization.py, glotaran/builtin/models/kinetic_spectrum/test/test_kinetic_spectrum_model.py, glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py, glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py, glotaran/builtin/models/kinetic_spectrum/test/test_spectral_relations.py, glotaran/cli/commands/pluginlist.py, glotaran/examples/sequential.py, glotaran/parameter/parameter.py, glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter.py, requirements_dev.txt, setup.py
This PR removes all dependencies to the `lmfit` package.
The optimization is now done by directly calling `scipy.optimize.least_squares`.
Changes
=======
* The `Parameter` class is no longer a child of `lmfit.Parameter`.
* `asteval` is used to evaluate parameter expressions.
* `optimize` now calls `scipy.optimize.least_quares` instead of using `lmfit.Minimizer`
* Few adaptions to tests due to small numeric differences
* Parameter and group labels now have restrictions to work with the new parameter expression scheme
Known Issues
===========
* The covariance matrix is no longer calculated
* The standart error of the optimized parameters is not calculated
This PR closes #491, closes #489 and closes #481.
=> Replace lmfit with scipy.optimize

glotaran/analysis/scheme.py, glotaran/analysis/test/test_scheme.py, glotaran/parameter/parameter_group.py, glotaran/parse/parser.py, glotaran/parse/test/test_model_parser_kinetic.py, glotaran/parse/test/test_model_spec_kinetic.yml, glotaran/parse/test/test_util.py, glotaran/parse/util.py
As a result of removing the need for !tuple parsing the yaml loading could be changed from yaml.load using the FullLoader to the safer yaml.safe_load (to all the security bot's delight).
A story in 2 parts
closes #503
=> Improve specification parsing

glotaran/analysis/optimize.py, glotaran/analysis/scheme.py, glotaran/analysis/test/test_optimization.py
Support for both Levenberg-Marquardt and LevenbergMarquardt but the correctly spelled Levenberg-Marquardt is preferred.
Closes #544
=> Fix typo in Levenberg-Marquardt

.github/workflows/CI_CD_actions.yml
I set [RTD to build on PR's](https://docs.readthedocs.io/en/latest/pull-requests.html) so we don't need the docs artifact anymore.
This PR is also a test for RTD to build the docs.
**Testing**
=> Remove 'docs' artifact from CI, in favor of RTD build on PR

.github/CODEOWNERS
Update to CODEOWNERS file following changes introduced by the merge of PR #556
PR 556 introduced a new IO system introducing new builtin modules and deprecated the parse module as well as builtin/file_formats
=> Update to codeowners

glotaran/analysis/problem.py, glotaran/io/prepare_dataset.py
Issue explained in #574 
Change call to numpy.linalg.svd to use full_matrices=False
Closes #574
=> Fix for excessive memory usage when creating results

docs/source/quickstart.rst
Replaced the warning indicating to not use it for science.
Added reference to v0.3 maintenance branch version of the README
=> Updated warning message in quickstart

HISTORY.rst
Just some changes to the history from the 0.3.1 release with added information about the 0.3.2 release.
**Testing**
=> Forwardport release info from 0.3.2 release

glotaran/parameter/parameter_group.py, glotaran/project/result.py, requirements_dev.txt, setup.cfg
Changes:
- Adds tabulate as a dependency
- `Result.markdown` now renders properly
- `ParameterGroup.markdown` is easier to read (both code and output)
A demo of how it looks [can be found at binder](https://mybinder.org/v2/gh/s-weigand/pyglotaran/tabulate?urlpath=lab%2Ftree%2Fdocs%2Fsource%2Fnotebooks%2Fquickstart.ipynb).
Compared it to [the current version](https://mybinder.org/v2/gh/glotaran/pyglotaran/main?urlpath=lab%2Ftree%2Fdocs%2Fsource%2Fnotebooks%2Fquickstart.ipynb), where the output of cell 16 showcases all changes.
To see the difference in plaintext (e.g. what a CLI user would see) use `print` instead of `print_md`.
**Testing**
closes #587
=> Use tabulate for table markdown formatting

glotaran/__init__.py, glotaran/builtin/io/ascii/wavelength_time_explicit_file.py, glotaran/builtin/io/csv/csv.py, glotaran/builtin/io/netCDF/netCDF.py, glotaran/builtin/io/sdt/sdt_file_reader.py, glotaran/builtin/io/sdt/test/test_file_readers.py, glotaran/builtin/io/yml/yml.py, glotaran/cli/commands/optimize.py, glotaran/cli/commands/pluginlist.py, glotaran/io/__init__.py, glotaran/io/decorator.py, glotaran/io/interface.py, glotaran/io/io.py, glotaran/io/register.py, pyproject.toml, setup.cfg
This PR address  some of the changes proposed in #586 
Since each commit has a district purpose, it might be easiest to review this PR commit by commit.
The other changes will be done in a separate PR since this will simplify the review.
**Testing**
not yet
=> Refactor io plugins

glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter_group.py
I just added your example from #538 as a test case and sorted the `child_group`s by the dict key before recursing them.
That way the markdown will always be sorted by the keys, but at least it will be the same no matter the order in the specs.
The test example looks like this:
* __irf__:
| _Label_   |   _Value_ |   _StdErr_ |   _Min_ |   _Max_ | _Vary_   | _Non-Negative_   | _Expr_   |
|-----------|-----------|------------|---------|---------|----------|------------------|----------|
| center    |       1.3 |          0 |    -inf |     inf | True     | False            | None     |
| width     |       7.8 |          0 |    -inf |     inf | True     | False            | None     |
* __j__:
|   _Label_ |   _Value_ |   _StdErr_ |   _Min_ |   _Max_ | _Vary_   | _Non-Negative_   | _Expr_   | …
=> Make ParameterGroup.markdown() indepedent of order parametergroups were added

setup.cfg
Just some tool configs for QA tools we plan to use but can't for the whole project because then the CI would fail.
When I write code for PR's I check that my code passes tests with `mypy`, `pydocstyle` and `darglint`, which we also plan to use.
So it would be nice to already have the configs in place, so I don't need to pass all the CLI flags each time
=> Add configs for tools planned to use

HISTORY.rst, README.md, glotaran/__init__.py
Bumped version to v0.3.3 and added release notes
v0.3.3 release notes draft: 
* Force recalculation of SVD attributes in scheme._prepare_data (#597)
* Remove unneeded check in spectral_penalties._get_area Fixes (#598)
* Added python 3.9 support (#450)
=> Prepare v0.3.3 release

glotaran/model/decorator.py, glotaran/model/util.py
Instead of relying on the `__annotations__` property to be the old style (python < 3.10), `wrap_func_as_method` needs to set `__annotations__` explicitly where needed.
Since only `Model` accesses `__annotations__` directly to use them, I don't think we need the same precautions for `ModelProperty` and `model.attributes`, since they use `_glotaran_model_attribute_typed` and `_glotaran_properties` internally, which then is used by `Model`.
**Testing**
closes #610
=> Make Models py310 ready

.gitignore, glotaran/builtin/io/yml/test/test_model_parser_kinetic.py, glotaran/builtin/io/yml/test/test_model_spec_kinetic.yml, glotaran/builtin/models/kinetic_image/initial_concentration.py, glotaran/builtin/models/kinetic_image/irf.py, glotaran/builtin/models/kinetic_image/k_matrix.py, glotaran/builtin/models/kinetic_image/kinetic_image_dataset_descriptor.py, glotaran/builtin/models/kinetic_image/kinetic_image_matrix.py, glotaran/builtin/models/kinetic_image/kinetic_image_megacomplex.py, glotaran/builtin/models/kinetic_image/kinetic_image_result.py, glotaran/builtin/models/kinetic_image/test/test_k_matrix.py, glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_result.py, glotaran/model/dataset_descriptor.py, glotaran/model/test/test_model.py
=> Fix several issues with KineticImage model

glotaran/builtin/io/folder/__init__.py, glotaran/builtin/io/folder/folder_plugin.py, glotaran/builtin/io/folder/test/test_folder_plugin.py, glotaran/builtin/io/yml/test/test_save_result.py, glotaran/plugin_system/io_plugin_utils.py, glotaran/plugin_system/project_io_registration.py, glotaran/plugin_system/test/test_io_plugin_utils.py, glotaran/project/test/test_result.py, pyproject.toml, setup.cfg
This plugin adds back the functionality from `glotaran.analysis.result.Result.save(result_path)` of pyglotaran `0.3.x`.
For `glotaran.io.save_result` it also adds inferring of `format_name=="folder"` if the provided `result_path` doesn't have an extension.
If `result_path` is a file it will raise a `ValueError`.
Usage equivalent to `result.save(result_path)`
```python
save_result(result_path=str(output_folder), result=result, allow_overwrite=True)
save_result(result_path=str(output_folder), result=result, format_name="folder", allow_overwrite=True)
save_result(result_path=str(output_folder), result=result, format_name="pyglotaran-legacy", allow_overwrite=True)
```
Also, the plugin is registered under the names `folder` and `pyglotaran-legacy`, thus if we want to fundamentally change the …
=> ✨ Add Folder plugin for save result

AUTHORS.rst
Address failing docs (on link testing), like e.g. here:
https://github.com/glotaran/pyglotaran/pull/617/checks?check_run_id=2248961079
**Error log**
```make
(         authors: line   21) broken    
http://www.nat.vu.nl/~ivo/ - HTTPConnectionPool(host='www.nat.vu.nl', port=80): Max retries exceeded 
with url: /~ivo/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34a281cee0>: 
Failed to establish a new connection: [Errno 110] Connection timed out'))
build finished with problems, 18 warnings.
make: *** [Makefile:42: linkcheck] Error 1
```
=> Remove unreliable URL from authors.rst

glotaran/project/result.py
Avoid crash in Result's print markdown method
Closes #629
=> Avoid crash in result markdown printing when optimization fails

CONTRIBUTING.rst, glotaran/__init__.py, glotaran/analysis/__init__.py, glotaran/builtin/__init__.py, glotaran/deprecation/__init__.py, glotaran/deprecation/deprecation_utils.py, glotaran/deprecation/modules/__init__.py, glotaran/deprecation/modules/glotaran_root.py, glotaran/deprecation/modules/test/__init__.py, glotaran/deprecation/modules/test/test_changed_imports.py, glotaran/deprecation/modules/test/test_glotaran_root.py, glotaran/deprecation/modules/test/test_project_result.py, glotaran/deprecation/modules/test/test_project_sheme.py, glotaran/deprecation/test/__init__.py, glotaran/deprecation/test/dummy_package/__init__.py, glotaran/deprecation/test/dummy_package/deprecated_module_attribute.py, glotaran/deprecation/test/test_deprecation_utils.py, glotaran/io/__init__.py, glotaran/project/result.py, glotaran/project/scheme.py, pyproject.toml, setup.cfg
This PR adds a deprecation framework and reintroduces the API of glotaran 0.3.x giving deprecation warnings when used, which instruct users how to change their code.
As usual with my PRs you best review it commit by commit, since they are structured by responsibility.
It might be best to start with the updated contributing docs where I describe the intended usage and then review the rest in order.
**Testing**
closes #588
=> 🩹 Add deprecation framework and readd 0.3.x API as deprecated

glotaran/builtin/models/kinetic_image/kinetic_image_matrix.py
A sensible threshold for applying backsweep being backsweep_period*rate>0.001
Needs profiling
Alternative for realizing #635
=> Do not apply backsweep with small rates

glotaran/__init__.py
The development version following the v0.3.x release will be "v0.4.0-dev"
Closes #638
=> :arrow_up: :construction: development version ++

.pre-commit-config.yaml, glotaran/builtin/io/ascii/wavelength_time_explicit_file.py
default branch (https://github.com/glotaran/pyglotaran/tree/main)
<details>
<summary>Details: </summary>
<details>
<summary><em>add path</em></summary>
```Shell
/home/runner/work/_actions/technote-space/create-pr-action/v2/node_modules/npm-check-updates/bin
```
</details>
<details>
<summary><em>pip install pre-commit</em></summary>
```Shell
Collecting pre-commit
Downloading pre_commit-2.12.0-py2.py3-none-any.whl (189 kB)
Collecting pyyaml>=5.1
Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
Collecting toml
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting identify>=1.0.0
Downloading identify-2.2.3-py2.py3-none-any.whl (98 kB)
Collecting cfgv>=2.0.0
Downloading cfgv-3.2.0-py2.py3-none-any.whl (7.3 kB)
Collecting virtualenv>=20.0.8
Downloading …
```
=> ⬆️ UPGRADE: Autoupdate pre-commit config

glotaran/builtin/io/sdt/sdt_file_reader.py, glotaran/builtin/io/sdt/test/test_file_readers.py
- index is calculated correctly + test
- differentiate between raw_data (np.ndarray) and data (xr.Dataset|xr.DataArray)
- warning raised at the correct stacklevel
**Testing**
closes #646
=> 🩹 Fix exception in sdt reader index calculation

.github/workflows/codeowners_validator.yml
Changed triggers for codeowners validation workflow:
- PRs use `pull_request_target` and explicit checkout
- `push` only triggers on `main`
- Dropped `schedule` since it runs on pushes to `main`
**Testing**
closes #506
=> 🔧 Change Codeowners Validator workflow to use pull_request_target

glotaran/plugin_system/base_registry.py, requirements_dev.txt, tox.ini
This feature is only useful if you run a subset of the tests, if you try to run them all `pytest` will just error.
- Allows deactivating of the plugin system
- Adds `pytest-env` as dev dependency
Plugins can be deactivated by changing the `pytest` config in  `tox.ini`
```ini
[pytest]
; Uncomment the following lines to deactivate pyglotaran plugins
env =
DEACTIVATE_GTA_PLUGINS=1
```
**Testing**
closes #661
=> 🧪 Add ability to deactivate the pluginsystem via env variable

.github/workflows/binder-on-pr.yml
This workflow will add a comment with a binder link to the branch for new PRs.
It will look like [this](https://github.com/s-weigand/jupyterlab_autosave_on_focus_change/pull/7#issuecomment-845714452)
**Testing**
=> 🔧 Add workflow to comment a link to binder on new PRs

docs/source/notebooks/plugin_system/plugin_howto_write_a_io_plugin.ipynb, docs/source/notebooks/quickstart/quickstart.ipynb, docs/source/user_documentation/using_plugins.rst, glotaran/builtin/io/ascii/wavelength_time_explicit_file.py, glotaran/builtin/io/csv/csv.py, glotaran/builtin/io/folder/folder_plugin.py, glotaran/builtin/io/netCDF/netCDF.py, glotaran/builtin/io/yml/test/test_save_result.py, glotaran/builtin/io/yml/yml.py, glotaran/io/__init__.py, glotaran/io/interface.py, glotaran/model/__init__.py, glotaran/parameter/test/test_parameter.py, glotaran/plugin_system/base_registry.py, glotaran/plugin_system/data_io_registration.py, glotaran/plugin_system/model_registration.py, glotaran/plugin_system/project_io_registration.py, glotaran/plugin_system/test/test_base_registry.py, glotaran/plugin_system/test/test_data_io_registration.py, glotaran/plugin_system/test/test_model_registration.py, glotaran/plugin_system/test/test_project_io_registration.py
This PR removes the issues I found with the new plugin system.
- `save` functions for IO plugins now have a natural python argument order ( (`<object>`, `<path>`) instead of (`<path>`, `<object>`))
- register functions don't trow a `PluginOverwriteWarning` if the plugin overwrites itself
- plugins now register at least twice, once as the developer intended and once under their full name (import path+instance postfix if it is an instantiated plugin like the IO plugins)
- new `set_plugin` functionality allowing to pin plugins and thus allowing reproducible analysis no matter which plugins have conflicts
- `project_io_plugin_table` and `data_io_plugin_table` now also show the plugin names if wanted, which helps to identify which plugin is used for which format
- `save` and `load` IO …
=> ♻️ Polish the plugin system

glotaran/deprecation/modules/test/test_model_base_model.py
Follow up on #671 
This test is mainly used for the tests to fail when we make a new release and the deprecation is overdue.
**Testing**
=> 🧪 Test depreciation of Model.simulate

.github/workflows/autoupdate-pre-commit-config.yml
pre-commit-ci will do the scheduled autoupdates from now on.
But in case we manually want to trigger it we still got this workflow to start an update PR from the actions tab on github.
**Testing**
=> 🔧 Remove the schedule from autoupdate-pre-commit-config

glotaran/deprecation/modules/test/test_glotaran_root.py, glotaran/parameter/parameter.py, glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter.py
- Ensure that Paremeter.label always is a str or None
- Improve Parameter typing (no more mypy error in parameter.py)
- Fix error message on invalid group label
- Improved test coverage
- Improved docstrings
Typing error reduction from [268](https://github.com/glotaran/pyglotaran/pull/444#issuecomment-850829451) to [253](https://github.com/s-weigand/pyglotaran/runs/2700885616?check_suite_focus=true)
**Testing**
closes #634
=> 👌 Ensure Parameter.label is str or None

glotaran/parameter/parameter_group.py
Just a mico change for better error messages I found when writing #687 .
For the error of the dummy example in #687 
Before:
`Cannot find parameter .bar`
After:
`Cannot find parameter 'bar'`
**Testing**
=> 👌 ParameterNotFoundException doesn't preprend '.' if path is empty

glotaran/analysis/simulation.py, glotaran/builtin/models/kinetic_image/kinetic_image_result.py, glotaran/builtin/models/kinetic_spectrum/spectral_shape.py, glotaran/builtin/models/kinetic_spectrum/test/test_coherent_artifact.py, glotaran/builtin/models/spectral/shape.py, glotaran/builtin/models/spectral/spectral_result.py, glotaran/builtin/models/spectral/test/test_spectral_model.py, pyproject.toml
This PR changes the implementation of the ~~lorentzian-bandshape~~ skewed-gaussian calculation to use a `1/cm` instead of an `nm` axis.
Thus the `location` and `width` now also need to be provided in `1/cm`.
Also, this adds [proper docstrings with the equations.
**Testing**
closes #685 
completes implementation of spectral model #674
=> 🩹 Fix calculation of skewed-gaussian in spectral model

.github/workflows/pr_benchmark.yml, .github/workflows/pr_benchmark_reaction.yml
Currently, the new `pr_benchmark` workflow is broken since workflows on the event `pull_request` from forks don't have access to secrets.
I missed this while testing since target and source repo were both my fork, and thus the PRs had privileged rights.
We don't want the benchmarks to run in a runner privileged rights (i.e. `pull_request_target`) but commenting and pushing need access to the secrets.
Thus commenting and pushing to the benchmarks repo need to be done in a privileged workflow.
Ref:
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
- The `pr_benchmark` workflow takes care of benchmarking and creation the comment body
- The `pr_benchmark_reaction` workflow comments on the PR and upload the HTML to a branch in `pyglotaran-benchmarks`
This PR still …
=> 🩹 Split up pr_benchmark workflow into two workflows

.github/workflows/pr_benchmark.yml, .github/workflows/pr_benchmark_reaction.yml
Instead of relying on `github.event.workflow_run.pull_requests[0].number` being the proper PR number the workflow ran on, we write it in a file and read it out, the same way we do it with the comment.
- Ensure that the correct PR number is present in the `pr_benchmark_reaction` workflow
- Fixed printing of comment body in the workflow (the problem was the multiline comment string is evaluated before executing the command, which resulted in a syntax error, now it gets wrapped in a python multiline string)
=> 🩹 Ensure that the PR number is present in the pr_benchmark_reaction workflow

glotaran/examples/sequential.py, glotaran/project/result.py
Micro cleanup, of deprecated usage in our code base.
- Change deprecated call to `model.simulate(...)` to `simulate(model, ...)`
- Arguments for `save_result` in the deprecation warning for `Result.save` are in the proper order
=> 🧹 Remove deprecated call to Model.simulate

glotaran/analysis/optimize.py
In today's meeting with @ism200 we found and solved the problem with the StdError of estimated parameters.
That said following [this StackOverflow aswer](https://stackoverflow.com/a/67023688/3990615) we might want to use a different implementation for cases "when the Jacobian is close to degenerate", but this would need benchmarking first.
Currently we use pretty much use the same as:
```python
chi2dof = np.sum(res.fun**2)/(res.fun.size - res.x.size)
cov *= chi2dof
perr = np.sqrt(np.diag(cov))    # 1sigma uncertainty on fitted parameters
```
Our code (reduced  version):
```python
chi_square = np.sum(ls_result.fun ** 2)
reduced_chi_square = chi_square / degrees_of_freedom
jacobian = ls_result.jac
covariance_matrix = np.linalg.inv(jacobian.T.dot(jacobian))
standard_errors = …
```
=> 🩹 Scale StdError of estimated parameters with RMSE

glotaran/project/result.py
Follow up, to #689 and mainly changes how the Result is auto rendered by in notebooks see #687
- "Model" section in notebook autorendered `Result` markdown (`Result._repr_markdown_`) now used h3 instead h1 `base_heading_level`
=> 👌 Add base_heading_level to Result.markdown

benchmark/benchmarks/integration/ex_two_datasets/benchmark.py, glotaran/analysis/optimize.py, glotaran/builtin/models/kinetic_spectrum/test/test_spectral_constraints.py
Follow up PR for #704 , which implements a more robust calculation of the `covariance_matrix` for results.
- 🧪 Adds benchmarks for `glotaran.analysis.optimize._create_result`
- 👌 Uses SVD of the estimated jacobian to calculate `covariance_matrix`
Not sure what was up with the calculation of the mask in the [original StackOverflow answer](https://stackoverflow.com/a/67023688/3990615)
```python
tol = np.finfo(float).eps*s[0]*max(res.jac.shape)
w = s > tol
```
So I changed it to
```python
w = s**2 > np.finfo(float).eps
```
which should be sufficient to prevent `ZeroDivisionError`.
If any of you can think of a reason why the biggest singular value and the shape of the jacobian might be of importance to create a filter mask please tell me 😄
=> 👌 More robust covariance_matrix calculation

.github/workflows/pr_benchmark.yml
Looks like the starting point of `asv` is exclusive so to benchmark the `0.4.0` release commit as well as the following commits we need to start at `v0.4.0^`.
- `pr_benchmark`workflow now includes the `0.4.0` release commit
=> 🚇Fixed starting point of benchamrks to include the 0.4.0 release

benchmark/benchmarks/integration/ex_two_datasets/benchmark.py
In #715 the benchmarks failed because they timed out after 60 seconds so to get results we need to raise the timeout.
- Raised PR benchmark to 300 seconds
=> 🚇 Raised benchmark timeout to 5min

.github/workflows/pr_benchmark.yml
Follow up PR for #723 
- The benchmark comment bot now compares against 0.4.0
=> 🩹 Compare benchmarks to 0.4.0 instead if upstream/main

.pre-commit-config.yaml
False usage of the regex might lead to false-positive matching. 'types_or' is the proper way to use pre-commit.
To get `type` of a file you have to use (identify)[https://github.com/pre-commit/identify] (dependency of `pre-commit` so it is already installed)
```console
$ identify-cli <file>
```
- All hooks now use `types_or` to match files
=> 👌 Fix pre-commit-config

.pre-commit-config.yaml, glotaran/deprecation/deprecation_utils.py, glotaran/plugin_system/data_io_registration.py, glotaran/plugin_system/model_registration.py, glotaran/plugin_system/project_io_registration.py, glotaran/utils/ipython.py, glotaran/utils/test/test_ipython.py, setup.cfg
Adds the QA tools [pydocstyle](https://github.com/PyCQA/pydocstyle), [darglint](https://github.com/terrencepreilly/darglint) and [mypy](https://github.com/pre-commit/mirrors-mypy) for the glotaran subpackages `plugin_system`, `utils` and `deprecation`.
This way we can activate them step by step for each module when it is up to standard.
- Adds pre-commit-hook `mypy` for `^glotaran/(plugin_system|utils|deprecation)`
- Adds pre-commit-hook `pydocstyle` for `^glotaran/(plugin_system|utils|deprecation)`
- Adds pre-commit-hook `darglint` for `^glotaran/(plugin_system|utils|deprecation)`
=> 🔧Add more QA tools for parts of glotaran

glotaran/__init__.py
For tests to pass you will need to reinstall glotaran
```
pip install -e .
```
since the metainformation get written at install time.
- Changed version from `0.4.0` to `0.5.0.dev0`
=> 🚧 Set version to 0.5.0.dev0

.github/workflows/full_benchmark.yml
When the "Full Benchmarks" workflow runs on forks (e.g. on schedule) it will fail since they don't have the token and/or rights to push the results to `pyglotaran-benchmarks`.
- "Full Benchmarks" workflow only runs on `glotaran/pyglotaran`
closes #751
=> 🩹 Deactivate Full Benchmarks workflow for forks

glotaran/builtin/megacomplexes/baseline/baseline_megacomplex.py
=> Small fix for baseline megacomplex

CONTRIBUTING.rst, glotaran/builtin/io/yml/yml.py, glotaran/deprecation/__init__.py, glotaran/deprecation/deprecation_utils.py, glotaran/deprecation/modules/builtin_io_yml.py, glotaran/deprecation/modules/test/__init__.py, glotaran/deprecation/modules/test/test_builtin_io_yml.py, glotaran/deprecation/modules/test/test_changed_imports.py, glotaran/deprecation/modules/test/test_glotaran_root.py, glotaran/deprecation/modules/test/test_project_result.py, glotaran/deprecation/modules/test/test_project_sheme.py, glotaran/deprecation/test/test_deprecation_utils.py, glotaran/utils/sanitize.py, tox.ini
To have a smooth transition for users the changes in the model specs were facilitated by `check_deprecations`
https://github.com/glotaran/pyglotaran/blob/bef7262348b9385b5abd1b2edf260b35ebaccc8a/glotaran/utils/sanitize.py#L221
which replaces the deprecated dict keys and values of the old spec with the new ones internally and should warn the user about the changed usage.
But the deprecation warnings were [filtered by python since the stack level didn't reach "usercode" (`load_model`)](https://docs.python.org/3/library/warnings.html#default-warning-filter).
This PR fixes this and adds tests that the warning originates from `load_model`, so users will see it.
Also, instead of `DeprecationWarning` we now raise `GlotaranApiDeprecationWarning` which is a subclass of `UserWarning` so it won't be …
=> 🩹Fix check_deprecations not showing deprecation warnings

glotaran/analysis/test/models.py, glotaran/analysis/util.py, glotaran/builtin/megacomplexes/damped_oscillation/__init__.py, glotaran/builtin/megacomplexes/damped_oscillation/damped_oscillation_megacomplex.py, glotaran/builtin/megacomplexes/damped_oscillation/test/test_doas_model.py, glotaran/builtin/megacomplexes/decay/decay_megacomplex.py, glotaran/builtin/megacomplexes/decay/irf.py, glotaran/builtin/megacomplexes/decay/test/test_decay_megacomplex.py, glotaran/builtin/megacomplexes/decay/util.py, glotaran/builtin/megacomplexes/spectral/test/test_spectral_model.py, glotaran/model/model.py, glotaran/test/test_spectral_penalties.py, setup.cfg
This PR adds the DampedOscillationMegacomplex model to pyglotaran.
- Add `DampedOscillationMegacomplex` as type `damped-oscillation`
- Small refactor in `analysis.util` and `builtin/megacomplex/decay`
=> Feature: Damped Oscillation Megacomplex

.pre-commit-config.yaml, pyproject.toml
Currently the way `interrogate` is run by `pre-commit` it auto-discovers `*.py` files in the repo root.
This can lead to errors with venvs.
- 🩹🔧  Changed interrogate hook to only run on glotaran folder
- 👌🚧 Raised interrogate threshold for 52% to 55% (current value 56.1%)
=> 🔧 Fix interrogate usage

docs/requirements.txt, docs/source/conf.py, docs/source/index.rst, docs/source/user_documentation/cli.rst, setup.cfg
Added docs for the CLI.
Links to the changed sections
- [Command-line Interface](https://pyglotaran--784.org.readthedocs.build/en/784/user_documentation/cli.html)
=> 📚 Add docs for the CLI

.github/workflows/pr_benchmark.yml, .github/workflows/pr_benchmark_reaction.yml
Running benchmarks on PRs takes forever to get feedback (~1h e.g. [here](https://github.com/glotaran/pyglotaran/runs/3382108255)) since it benchmarks each commit in between.
The most important information are the benchmark of the last release and the current commit before merging.
Thus we can omit running the benchmarks for all steps in between.
If more insight is needed at which specific commit in a PR a performance regression occurred it can always be run locally.
- Only run base compare commit (`v0.4.0`) and last `HEAD` commit on PR benchmark
=> 🚇 Speedup PR benchmark

glotaran/model/clp_penalties.py
The deprecated equal_area_penalties would be called in lieu of the new clp_area_penalties function
The pyglotaran-examples have in their model still equal_area_penalties which is correctly swapped with clp_area_penalties but them model.equal_area_penalties  was still called in some places instead of model.clp_area_penalties
closes #789
=> Update calls to clp_area_penalties where deprecated func is called

glotaran/builtin/megacomplexes/decay/k_matrix.py
Avoiding the use of set to improve ordering
Refactor at least guarantees better than random ordering using list(set(x))
TODO: further improve ordering to use initial_concentrations ordering
closes #787
=> Improve ordering in k_matrix involved_compartments function

glotaran/builtin/models/kinetic_image/k_matrix.py
Avoiding the use of set to improve ordering
Refactor at least guarantees better than random ordering using list(set(x))
Backport of a6a5a510cc2e95b8d81b32413824a59093ad5522 for improved consistency between v0.4.1 maintenance branch and staging-to-become-v0.5.0
=> [Backport] Improve ordering in k_matrix involved_compartments function

glotaran/deprecation/modules/builtin_io_yml.py, glotaran/deprecation/modules/test/test_builtin_io_yml.py
Follow-up PR for #775 .
The replacement wor backward compatibility (`type: spectrum` -> `default-megacomplex: spectral`) in #775 was wrong, since the old way (`v0.4.0`) to define a spectral model was `type: spectral-model`.
This error slipped since we do not yet have integration tests for spectral models/megacomplexes.
- Fixes broken backward compatibility for `0.4.0` spectral model specs.
=> 🩹 Fix wrong deprecation replacement for spectral-model spec

glotaran/analysis/problem_grouped.py
Get rid of all things set()
closes #787
=> Fix compartment ordering randomization due to use of set

glotaran/analysis/problem_grouped.py, glotaran/analysis/problem_ungrouped.py, glotaran/analysis/util.py, glotaran/model/clp_penalties.py
This fix reproduces the area penalty behavior that was in v0.4.1 when multiple datasets are involved.
The 'equal area penalty' is calculated on a per dataset basis.
- Calculate in `calculate_clp_penalties` the clp penalties on a per dataset level
closes #800
=> Improvements to application of clp_penalties (equal area)

.github/test_result_consistency.py, .github/workflows/integration-tests.yml, .gitignore, CONTRIBUTING.rst, requirements_dev.txt, tox.ini
Right now the integration tests only show breaking API changes, but checking validity is still a manual task.
This PR adds a way to compare the results to a "gold standard" (tag, branch, commit) set by [this workflow](https://github.com/glotaran/pyglotaran-examples/actions/workflows/update_compare_results.yml) on the `pyglotaran-examples` repo.
- Adds numerical comparison to "gold standard" results defined by `pyglotaran-examples`
=> 🧪🚇 Add integration test result validation (maintain/0.4.1)

.github/test_result_consistency.py, .github/workflows/integration-tests.yml, .gitignore, CONTRIBUTING.rst, requirements_dev.txt, tox.ini
Right now the integration tests only show breaking API changes, but checking validity is still a manual task.
This PR adds a way to compare the results to a "gold standard" (tag, branch, commit) set by [this workflow](https://github.com/glotaran/pyglotaran-examples/actions/workflows/update_compare_results.yml) on the `pyglotaran-examples` repo.
- Adds numerical comparison to "gold standard" results defined by `pyglotaran-examples`
closes #753
=> 🧪🚇 Add integration test result validation

glotaran/builtin/megacomplexes/baseline/baseline_megacomplex.py, glotaran/builtin/megacomplexes/coherent_artifact/coherent_artifact_megacomplex.py, glotaran/builtin/megacomplexes/spectral/spectral_megacomplex.py, glotaran/model/constraint.py, glotaran/model/interval_property.py, glotaran/model/item.py
1. Parameters differ from overridden 'index_dependent' method
- glotaran/builtin/megacomplexes/baseline/baseline_megacomplex.py
- glotaran/builtin/megacomplexes/coherent_artifact/coherent_artifact_megacomplex.py
- glotaran/builtin/megacomplexes/spectral/spectral_megacomplex.py
2. Parameters differ from overridden 'applies' method
- glotaran/model/constraint.py
3. Dangerous default value {} as argument
- glotaran/model/item.py
1. benchmark/pytest/analysis/test_problem.py
- Unused variable 'run' 
- is used by benchmark decorator
2. Unused variable 'Dummy'
- glotaran/plugin_system/test/test_megacomplex_registration.py
- is needed for plugin_system test
=> Fix codacy issues on staging

.pre-commit-config.yaml, glotaran/deprecation/deprecation_utils.py
Just some more tests for common errors ^^
- Added additional hooks from [`pygrep-hooks`](https://github.com/pre-commit/pygrep-hooks)
=> 🧪 Add more tools from the 'pygrep-hooks' pre-commit hook

.sourcery.yaml
Added sourcery config file and added 'simplify-boolean-comparison' to ignore.
This prevents expressions like `if something is True` to be refactored.
'if something is True' prevents bugs where something is a callable, where 'if something():' would evaluate to False but 'if something:' evaluated to true since the callable object exists.
While using this explicit syntax creates a longer instruction list, the performance impact is neglectable.
```python
In [1]: from dis import dis
In [2]: def foo():
...:     var = True
...:     if var is True:
...:         return False
...:
In [3]: def bar():
...:     var = True
...:     if var:
...:         return False
...:
In [4]: dis(foo)
2           0 LOAD_CONST               1 (True)
2 STORE_FAST               0 (var)
3           4 LOAD_FAST …
```
=> 🔧 Added sourcery config file

.github/workflows/pr_benchmark.yml
Since [`staging` finally got merged into `main` 🎉 ](https://github.com/glotaran/pyglotaran/pull/778 ) we can use `main` as the comparison standard for PR instead of the `v0.4.0` release.
For the updated comment [see](https://github.com/glotaran/pyglotaran/pull/831#issuecomment-922339404).
- 🚇 Use main and comparison for PRs
- 🚇 Compare main against last release (tag)
=> 🚇 Retarget PR benchmarks to main

docs/source/notebooks/quickstart/model.yaml
In  [quickstartdocs](https://pyglotaran.readthedocs.io/en/latest/notebooks/quickstart/quickstart.html#) this error was displayed:
```
/tmp/ipykernel_502/993879133.py:1: GlotaranApiDeprecationWarning: Usage of 'type: kinetic-spectrum' was deprecated, use 'default-megacomplex: decay' instead.
This usage will be an error in version: '0.7.0'.
model = load_model("model.yaml")
````
- 📚fixed deprecated model in quickstart
=> 📚fixed deprecated model in quickstart

glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter_group.py
Currently, the repr of `ParameterGroup` doesn't work properly when it is created with `from_list`.
```python
In [1]: from glotaran.parameter import ParameterGroup
In [2]: ParameterGroup.from_list([2.0,3.0])
Out[2]: ParameterGroup.from_dict({})
```
With this fix in place it looks like this:
```python
In [1]: from glotaran.parameter import ParameterGroup
In [2]: ParameterGroup.from_list([2.0,3.0])
Out[2]: ParameterGroup.from_list([['1', 2.0], ['2', 3.0]])
```
- 🩹 Fix ParameterGroup repr when created with 'from_list'
=> 🩹 Fix ParameterGroup repr when created with 'from_list'

CONTRIBUTING.rst, glotaran/deprecation/__init__.py, glotaran/deprecation/deprecation_utils.py, glotaran/deprecation/modules/test/test_model_model.py, glotaran/deprecation/test/test_deprecation_utils.py, glotaran/model/dataset_model.py, glotaran/model/model.py, glotaran/project/scheme.py, glotaran/project/test/test_scheme.py
Currently (7c5573d4f00cdad70c9a4e4114accb5fab702fe3) the model properties `model_dimension` and `global_dimension` are just removed without any help on what to do.
Since at the scope of a newly created model there isn't enough information to keep the API intact, we will at least throw an error with the appropriate new usage information.
The easiest way to review this PR should be per commit. 🥂 
- ♻️ Factored out glotaran v1.0.0 mocking to a fixture
- ♻️ Factored out overdue deprecation checking to is own function
- 📚🩹 Fixed typo in error message and wrong variable name in docstrings
-  ✨ Added 'raise_deprecation_error' 
- 📚 Added docs on when to use 'raise_deprecation_error'
- 🩹 Fix false positive pytest.raises tests in test_deprecation_utils
- 📚🩹 Fixed mentioning of dataset descriptor in …
=> 🗑️ Deprecate Model properties model_dimension and global_dimension

glotaran/analysis/test/test_constraints.py, glotaran/analysis/test/test_relations.py, glotaran/analysis/util.py, glotaran/builtin/io/yml/test/test_model_parser.py, glotaran/builtin/io/yml/test/test_model_spec.yml, glotaran/deprecation/modules/builtin_io_yml.py, glotaran/deprecation/modules/test/test_builtin_io_yml.py, glotaran/model/model.py, glotaran/model/test/test_model.py
♻️ Refactor model specification
- ♻️ In model spec changed relation to clp_relations
- ♻️ In model spec changed constraints to clp_constaints
closes #821
=> ♻️ Refactor/821 refactor model spec

glotaran/builtin/megacomplexes/damped_oscillation/damped_oscillation_megacomplex.py
Refactor and fix `calculate_damped_oscillation_matrix_gaussian_irf` in `damped_oscillation_megacomplex.py`
- 🩹 Fix for time-reversed oscillations
- ♻️ Improve numerical stability of calculation
For code related to this feature see: 
- https://github.com/glotaran/pyglotaran-examples/pull/44
- https://github.com/glotaran/pyglotaran-examples/commit/49ac3bf2908dc260900e24080d38696bee78a4b8
=> ♻️ Refactor/calc doas with irf

glotaran/parameter/parameter.py, glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter.py
The naive approach using `expression.replace` lead to problems when an expression for a parameter was part of another expression for a parameter.
Example:
The expression:
`"100 - $inputs1.s1 - $inputs1.s3 - $inputs1.s8 - $inputs1.s12"`
should have been transformed to:
`"100 - group.get('inputs1.s1').value - group.get('inputs1.s3').value - group.get('inputs1.s8').value - group.get('inputs1.s12').value"`
but instead was transformed to:
`"100 - group.get('inputs1.s1').value - group.get('inputs1.s3').value - group.get('inputs1.s8').value - group.get('inputs1.s1').value2"`
Since `"inputs1.s1"` partially matches `"inputs1.s12"`
I also moved the regex compiling out of the class, so it only gets executed when the module is loaded.
- 🩹♻️🧪 Fixed Parameter expression transformation
- 👌 Added missing …
=> 🩹 Fix parameter expression parsing

glotaran/builtin/io/netCDF/netCDF.py
avoid file locking when calling xarray.open_dataset
closes #847
=> 🩹 Use a context manager when opening a nc dataset

.github/workflows/integration-tests.yml
Currently, the integration tests CI installs the latest versions available and allowed by `pyglotaran`s `setup.cfg`. I case of a breaking update in a dependency this breaks all CI workflows, thus it is better to use the pinned versions from 'requirements_dev.txt' so only breaking changes break the CI.
An example can be seen in PR #890 and [this CI run](https://github.com/glotaran/pyglotaran/runs/4119745211?check_suite_focus=true), where the CI breaks because of a new version of `xarray` which is unrelated to the PR itself.
- 🚇🩹 Use pinned version of dependencies to run integration tests 
- 🚇👌 Add step to show installed packages for debugging purposes
=> 🚇🩹 Use pinned versions of dependencies to run integration CI tests 

setup.cfg
The `0.20.0` release introduced a bug breaking plotting in integration tests (see also #892 ).
By now this [bug has been fixed](https://github.com/pydata/xarray/pull/5948) but no new version of `xarray` has yet been released, so we should disallow the breaking versions.
If a fixed version has been released we can think of raising the minimal version.
- 🚧 Disallow xarray versions breaking plotting in integration tests
=> 🚧 Disallow xarray versions breaking plotting in integration tests

glotaran/model/model.py, glotaran/model/test/test_model.py
Adds the `Dataset Groups` subsection to the markdown representation of model (used in the markdown report).
- 🧪 Added failing test case showing the expected output of Model.markdown
- 🩹 Change Model.markdown to satisfy the test
closes #885
=> 🩹 Fix 'dataset_groups' not shown in model markdown

.github/workflows/pr_benchmark_reaction.yml
This change was needed due to updating to actions/github-script@v5 (#845, merged via #884 )
- 🩹 Fixed artifact download in pr_benchmark_reaction workflow
=> 🩹 Fixed artifact download in pr_benchmark_reaction workflow

glotaran/builtin/io/folder/folder_plugin.py, glotaran/builtin/io/yml/test/test_save_result.py, glotaran/builtin/io/yml/test/test_save_scheme.py, glotaran/builtin/io/yml/yml.py, glotaran/deprecation/modules/test/test_project_scheme.py, glotaran/io/__init__.py, glotaran/model/model.py, glotaran/parameter/parameter_group.py, glotaran/parameter/parameter_history.py, glotaran/plugin_system/data_io_registration.py, glotaran/plugin_system/io_plugin_utils.py, glotaran/plugin_system/project_io_registration.py, glotaran/plugin_system/test/test_data_io_registration.py, glotaran/plugin_system/test/test_project_io_registration.py, glotaran/project/dataclass_helpers.py, glotaran/project/result.py, glotaran/project/scheme.py, glotaran/project/test/test_dataclass_helpers.py, glotaran/project/test/test_result.py, glotaran/project/test/test_scheme.py, glotaran/typing/__init__.py, glotaran/typing/protocols.py, glotaran/typing/types.py, glotaran/utils/io.py, glotaran/utils/test/test_io.py
This PR removes the file representation fields from  the augmented dataclasses completely and thus simplifies the API
from:
https://github.com/glotaran/pyglotaran/blob/ded0711b0bc4c133636b02a0a1b7b407a6a26c99/glotaran/builtin/io/yml/test/test_save_scheme.py#L38-L45
to
```python
scheme = Scheme(
model,
parameter,
{"dataset_1": dataset},
)
```
- There now is  a `glotaran.typing` module
- `FileLoadable` classes (`Model`, `ParameterGroup`, `Scheme`, `Result`, `DatasetMapping`) know their own file origin
- There is a new convenience io function `load_datasets` which can load datasets in bulk, which then can be consumed by Scheme
- ♻️👌 Removed file fields in ProjectIo like classes and used unified field
- ♻️🔌 Refactored load_dataset to always return xr.Dataset
- ♻️ Added type 'StrOrPath' and …
=> ♻️ Refactor Result and Scheme loading to to use 'file' fields

glotaran/deprecation/modules/test/test_parameter_parameter_group.py, glotaran/model/test/test_model.py, glotaran/parameter/parameter.py, glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter.py, glotaran/parameter/test/test_parameter_group.py, glotaran/parameter/test/test_parameter_group_rendering.py
This PR streamlines the to and from dataframe methods of parameter group and ensures all parameter properties are included in the dataframe.
- Added methods `as_dict` and `from_dict` to `Parameter`
- Added methods `to_parameter_dict_list` and `from_parameter_dict_list` to `ParameterGroup`
- Refactored `to_dataframe` and `from_dataframe` to use new methods
- Refactored parameter tests
- Load standard error from df
- save standard error to parameter df
- `to_datafame` has a switch `as_optimized` now which defaults to true, a later pr must adapt the io API
- Added `Parameter.markdown` as basis for follow up PR
- This NOT used `ParameterGroup` to markdown. It is intended to be used by `Model.markdown`
closes #902
u
=> Serveral refactorings in `glotaran.Parameter`

glotaran/model/model.py, glotaran/parameter/parameter_group.py, glotaran/parameter/parameter_history.py, glotaran/project/result.py, glotaran/project/scheme.py, glotaran/project/test/test_dataclass_helpers.py, glotaran/utils/io.py
In python 3.9.7 (currently the only python 3.9 version on conda) [there was a bug](https://github.com/python/cpython/pull/27545) that ignores the __init__ method of classes that inherit from a Protocol.
This lead to the following error (discovered by @jsnel )
```python
TypeError: Protocols cannot be instantiated
```
Rather than restricting the usable python versions for typing sake, I will file an issue at `mypy` since the conformity with protocols should be picked up automatically.
- 🩹 Removed inheriting from 'FileLoadableProtocol'
=> 🩹 Remove inheriting from 'FileLoadableProtocol'

.pre-commit-config.yaml, glotaran/builtin/io/yml/test/test_model_parser.py, glotaran/builtin/io/yml/test/test_model_spec.yml, glotaran/model/item.py, glotaran/model/megacomplex.py, glotaran/model/model.py, glotaran/model/property.py, glotaran/model/test/test_model.py, glotaran/model/test/test_model_property.py, glotaran/model/util.py, glotaran/parameter/parameter.py, requirements_dev.txt, setup.cfg
This PR refactors the `ModelProperty` class.
- Markdown printing of `Model` has been changed
- Beautification is left for followup PR
closes #901
=> Refactored ModelProperty.

glotaran/parameter/parameter.py, glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter_group_rendering.py
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._
Please provide enough information so that others can review your pull request:
Explain the **details** for making this change. What existing problem does the pull request solve?.
- Table headers in markdown don't use a mix of abbreviations and spelled out names but only spelled out names
- Expression column doesn't evidently render as latex when 2 or more parameters are present
- Numbers get formatted as `.3e` by default
- User can decide on the float precision of the markdown table by passing `float_format`
closes #916
=> 👌 Improve ParameterGroup markdown rendering

requirements_dev.txt
This is just a combination PR of:
- #915 
- #909 
- #908 
- #890
=> ⬆️ Combined dependabot updates

glotaran/utils/io.py, glotaran/utils/test/test_io.py
This fixes the crash of `save_result` when the original data and the result path are on different drives on windows.
~The commit e431760a9646e3ca311107926cafa4a952092416 is optional.~
- 🩹 Made 'relative_posix_path' more stable on windows
~- ♻️ Changed save_result folder to use the result.data for scheme.data~
closes #924
=> 🩹 Fix save_result crashes on Windows if input data are on a different drive than result

changelog.md, glotaran/__init__.py, glotaran/builtin/models/kinetic_image/kinetic_image_result.py
It was [found](https://github.com/glotaran/pyglotaran/pull/860#issuecomment-985467588) in #860 that the a_matrix when calculated for result saving was calculated without normalized initial_concentrations while the calculation for the optimization was (correctly) using the normalized version. Fixing this bug in #927 then breaks result consistency checking for some case studies, thus requiring backporting of this bugfix to the 0.4 maintenance branch which we continue to use for result/consistency checking.
=> 🚀🩹 v0.4.2 release preparation and bugfix backport for result consistency checking purposes

.github/test_result_consistency.py, changelog.md
Update float_resolution for comparison of spectral values, fixing issue #937 identified in #936
Refer to comment in #936 reproduced below:
After the update we find that the result comparison still fails but only for a singular data point in one of the examples (log below). Digging a little deeper (looking at the plot) we find that the point of failure is at a place were the spectral value in question is very small (~-1.497), compared to the overall maximum of the spectrum (~7500). However, the spectra are compared locally (per wavelength) and the absolute tolerance for the comparison between results is scaled with the local value of the data, meaning that the tolerance for a point close to zero is much tighter than the tolerance for a point near the maximum. This is a point where the …
=> 🚇Update test_result_consistency

.github/test_result_consistency.py, changelog.md
Result comparison was too sensitive to numerical fluctuation, the tolerances needed to be adjusted on both the v0.4 maintenance branch as well as main. 
PR targeting v0.4 maintenance: 
- #936 
This PR also forward ports missing changelog entries from the v0.4 maintenance branch
Closes #937
=> 🚧 Forward port Improve result comparison workflow and v0.4 changelog

glotaran/builtin/megacomplexes/decay/util.py
- Use normalized Irf in creation of resulting A matrix and DAS
- Bugfix also back-ported to v0.4 maintenance branch in #935 
Closes #926, #932
=> 🩹 Bugfix Use normalized initial_concentrations in result creation for decay megacomplex

changelog.md, glotaran/__init__.py
Update changelog for 0.5.1 release and set version accordingly.
- 🩹 Bugfix Use normalized initial_concentrations in result creation for decay megacomplex (#927)
- 🩹 Fix save_result crashes on Windows if input data are on a different drive than result (#931)
closes #926
=> 🚀 Prepare v0.5.1 bugfix release

.pre-commit-config.yaml, MANIFEST.in, changelog.md, pyproject.toml
This fixes `changelog.md`  missing from the tarball and adds an additional tool to check that all need files are included in the distribution.
- 🩹 Changed old HISTORY.rst to changelog.md in manifest
- 🔧 Added 'check-manifest' pre-commit hook to check for missing files in the distribution
=> 🔧 Improve packaging tooling

changelog.md, glotaran/analysis/optimization_group_calculator_linked.py
- Indexing did not match content of _group.matrices (list of CalculatedMatrix objects)
- Dimension did not match (for guidance spectra) (global_dimension_index appeared to be missing
Closes #950
=> 🩹Fix bug in create_index_independent_result_dataset

.sonarcloud.properties, changelog.md
Due to duplications that aren't even part of a PR sonarcloud is failing its test (e.g. #958 )
By adding the test files which should be verbose and readable, I hope we can get around this issue.
- 🔧 Exclude test files from duplication checks
=> 🔧🚇 Exclude test files from duplication checks on sonarcloud

benchmark/pytest/analysis/test_optimization_group.py, glotaran/builtin/io/yml/test/test_save_scheme.py, glotaran/deprecation/deprecation_utils.py, glotaran/deprecation/modules/examples/sequential.py, glotaran/deprecation/modules/test/test_changed_imports.py, glotaran/deprecation/modules/test/test_parameter_parameter_group.py, glotaran/deprecation/modules/test/test_project_scheme.py, glotaran/parameter/parameter.py, glotaran/testing/simulated_data/parallel_spectral_decay.py, glotaran/testing/simulated_data/sequential_spectral_decay.py, glotaran/testing/simulated_data/shared_decay.py
Improve spelling, fix typos.
Specific changes:
- Use parameters instead of parameter where it makes sense.
- Avoid using wildcards when importing from module
=> Follow up PR#866 ♻️ - 👌Minor cosmetic changes

.github/workflows/CI_CD_actions.yml, .pre-commit-config.yaml, changelog.md
While it is important that we check if all files we want to bundle are actually bundled in the distribution, checking this in pre-commit can be cumbersome.
E.g. you were working on a PR and when you got it to work the way you want you to commit different small changes in contextual closed commits. If you added new files which you don't want to add in this commit `check-manifest` won't allow you to make this commit since it looks at all files and not only the tracked ones.
This in turn means that you need to make big commits or use the `--no-verify` flag which both can lead to bad commits.
- 🔧🚇 Only run check-manifest on the CI
=> 🔧🚇 Only run check-maifest on the CI

changelog.md, glotaran/builtin/io/folder/folder_plugin.py, glotaran/builtin/io/folder/test/test_folder_plugin.py, glotaran/builtin/io/yml/test/test_save_result.py, glotaran/builtin/io/yml/yml.py, glotaran/deprecation/__init__.py, glotaran/io/__init__.py, glotaran/io/interface.py, glotaran/plugin_system/io_plugin_utils.py, glotaran/plugin_system/project_io_registration.py, glotaran/plugin_system/test/test_io_plugin_utils.py, glotaran/plugin_system/test/test_project_io_registration.py, glotaran/project/result.py, glotaran/project/test/test_result.py
My take on #874 😝 
The main difference is `data_filter` is applied on the `save_result` level instead of adding an unused keyword to all `save_dataset` methods.
I also deprecated the `legacy` plugin and made `folder` throw a warning when not used from inside another plugin, thus promoting `yml` to the goto `save_result` plugin, which will make the transition to project easier.
The `folder` plugin now also doesn't save `model.yml` nor `scheme.yml`, that way it can easier be reused in different plugins.
-  🚧 Salvage parts of PR 874 
- 🧪 Removed part of a test which fails and should fail 
- 👌 Restored wanted functionality
- 👌 Homogenized save_result return value to always be a list of strings
- 👌 Properly reexport functionality from glotaran.deprecation
- 🗑️ Deprecated save_result legacy …
=> 👌 Add SavingOptions to save_result API 

setup.cfg
Currently our [ASV workflow fails](https://github.com/glotaran/pyglotaran/runs/4990008398?check_suite_focus=true) since `xarray==0.21.0` had a [mishap forgetting to add `packaging` as a dependency](https://github.com/pydata/xarray/pull/6207). 
Happens to the best of us, especially since `packaging` piggybacks on `pytest` so you won't see this error in any test environment, and even in our docs something added it, so they pass.
Anyway, to have our benchmarks work and go on with our stuff, let's just disallow this version until everything is sorted out.
If `xarray` decides to make a  [post-release](https://www.python.org/dev/peps/pep-0440/#post-releases), we can simply revert this change. If they rather choose to make a bugfix release it will stay in.
- 🩹 Disallow xarray 0.21.0
=> 🩹 Disallow xarray 0.21.0 in setup.cfg

.github/workflows/CI_CD_actions.yml, changelog.md
Since dependabot opens its branches for PRs on our repo and we require a linear history builds on `push` and `pull_request` are the same. And by deactivating the CI for the `push` event on dependabot branches we save time and energy.
- 🚇👌 Exclude dependabot push CI runs
=>  🚇👌 Exclude dependabot push CI runs

.github/workflows/doxygen.yml
Since we most of the time don't make use of the Doxygen generated callgraphs we don't need to always run the workflow.
Thus is created a [github environment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) called `Debug` which needs approval from a member of @glotaran/contributors to run.
That way Doxygen won't run until we approve/request it.
- 🚇 Only run doxygen workflow when requested
=> 🚇 Only run doxygen workflow when requested

.github/dependabot.yml, .github/workflows/CI_CD_actions.yml, changelog.md, requirements_dev.txt, setup.cfg, tox.ini
[Numba 0.55.0 added support for python 3.10](https://github.com/numba/numba/releases/tag/0.55.0) which means so can we
- 🚇🧪 Add tests for python 3.10
- ⬆️ Raised max supported python version to <3.11
- ⬆️ Unpin `setuptools`
Using an old version of `setuptools` caused a lot of import errors in python 3.10
Pinning the version of `setuptools` goes back to the time when we still had c-extensions, so it is safe to unpin it
=> ✨Add Python 3.10 support

.github/workflows/doxygen.yml
As requested by @jsnel this changes the Doxygen workflow to truly only run when requested.
The problem with the current implementation (#979 ) via github environment is that the UI never gets to the finished green checkmark state, but waits forever for the workflow to be approved.
This makes it hard to spot which PR is ready to be merged in the PR overview.
The new implementation allows specifying a repository to build the oxygen docs for (default `glotaran/pyglotaran` but could also be a fork) and a pr nr (default "" which uses the branch used to dispatch the workflow from).
- 🚇👌 Reworked doxygen workflow to be 'workflow_dispatch' but work with PRs
=> 🚇👌 Run Doxygen workflow only on  'workflow_dispatch'

.github/workflows/CI_CD_actions.yml, .github/workflows/integration-tests.yml, .github/workflows/pr_benchmark.yml
Looks like specifying `branches-ignore` on the push event also prevents it from running on pushed tags.
This prevents the release workflow from publishing to PyPI.
- [🩹🚇 Fixed release pipeline not running on push tag](https://github.com/glotaran/pyglotaran/commit/9b42d4db638258c86f79d9bdeae86bd41cf7b7c0)
- [🩹🚇 Exclude asv version 0.5](https://github.com/glotaran/pyglotaran/pull/990/commits/98fce429c723e9d6f4108fd36eaafbb8e0984cd2) (there was a [mishap when packaging](https://github.com/airspeed-velocity/asv/pull/1013) resulting in a broken package)
=> 🩹🚇 Fix release pipeline not running on push tag

changelog.md, glotaran/analysis/optimize.py, glotaran/parameter/parameter.py, glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter_group_rendering.py, glotaran/project/result.py, glotaran/utils/sanitize.py, glotaran/utils/test/test_sanitize.py
Just some minor visual changes to the markdown representation of Result, Parameter and ParameterGroup.
Requested by @ism200 
Before:
After:
- [👌 Renamed 'Number of variables' to 'Number of parameters' in result md](https://github.com/glotaran/pyglotaran/commit/d8cfcc808ae12229697da70f295aef1ac272940d)
- [👌 Remove 'RMSE additional penalty' from report if empty](https://github.com/glotaran/pyglotaran/commit/cce088a6dd6e5cceded55a71b5cd666a1e0234c5)
- [👌 Added t-value to parameter markdown reprs](https://github.com/glotaran/pyglotaran/commit/1d1c9a74c122550c138d9e06e41311294dc01bfa)
- [🚧 Add sourcery skip to code that should not be refactored](https://github.com/glotaran/pyglotaran/pull/1012/commits/5b84045b1215f1612093e007c054d66a020bd215)
=> 👌 Improve Result, Parameter and ParameterGroup markdown

changelog.md, docs/remove_notebook_written_data.py, docs/source/conf.py, tox.ini
Currently [docs on main are failing](https://readthedocs.org/projects/pyglotaran/builds/16338003/) due to an existing `*.nc` file produced when running the notebook. This most likely is due to caching done by read the docs.
To (hopefully) prevent this error the docs (`conf.py`) should clean the file before building.
- [👌📚🚇 Auto remove notebook written data when building docs](https://github.com/glotaran/pyglotaran/commit/eab81f788c894807c80dff4858d55d7470993834)
=> 👌📚🚇 Auto remove notebook written data when building docs

.github/test_result_consistency.py, .github/workflows/integration-tests.yml, changelog.md
The examples action which creates the results for result consistency checks has a [new feature to create the list of possible examples](https://github.com/glotaran/pyglotaran-examples/pull/54) that way we don't need to manually manage [this list](https://github.com/glotaran/pyglotaran/blob/c8b993b753a4fe9cba64a1c5bd0fb461f3dac05c/.github/workflows/integration-tests.yml#L17), which currently is missing the DOAS example.
- [👌🚇 Changed integration tests to use self managed examples action](https://github.com/glotaran/pyglotaran/commit/77b03e4a44663b4b357b50d554d3bb5f9d34bb1f)
=> 👌🚇 Change integration tests to use self managed examples action

glotaran/builtin/io/folder/folder_plugin.py, glotaran/builtin/io/folder/test/test_folder_plugin.py, glotaran/builtin/io/yml/test/test_save_model.py, glotaran/builtin/io/yml/test/test_save_result.py, glotaran/builtin/io/yml/utils.py, glotaran/builtin/io/yml/yml.py, glotaran/model/item.py, glotaran/model/model.py, glotaran/model/property.py, glotaran/model/test/test_model.py, glotaran/parameter/parameter.py, glotaran/project/__init__.py, glotaran/project/generators/generator.py, glotaran/project/project.py, glotaran/project/project_data_registry.py, glotaran/project/project_model_registry.py, glotaran/project/project_parameter_registry.py, glotaran/project/project_registry.py, glotaran/project/project_result_registry.py, glotaran/project/result.py, glotaran/project/test/test_project.py, glotaran/utils/io.py
This PR adds a basic `Project` class.
The `Project` class is intended to serve as a standard API to `pyglotaran`.
Add the moment, using `pyglotaran` as a python package requires alot of imports from different sub packages. This ok because our current API is kind of a "super user" API. The nature of it is that it changes alot, which is not user friendly. On the other hand side, we now have a deprecation framework, which is very useful but slows down development.
The `Project` class mitigates this. It is designed as a user API, escpeicially with having GUIs and stuff in mind. It is meant to be a representation of the actual iterative process of global target analysis. 
The `Project` class as implemented in this PR is basically a kind of "API aggregator" plus a KISS principle based …
=> ✨ Project Class

changelog.md, glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter_group.py, glotaran/project/test/test_result.py
This PR started as fix for #933, during which #1042 was discovered.
For the result comparison to succeed we need to update the gold standard (e.g. [manually add the missing `osc` to the labels of the parameter saved in the results](https://github.com/glotaran/pyglotaran-examples/pull/63)).
- [🧪 Added failing test for issue 933](https://github.com/glotaran/pyglotaran/commit/b6b3dd1588ae36fa50467c4712b7702b01ef7cd1)
- [🩹 Fixed issue in ParameterGroup.get with degraded full_label](https://github.com/glotaran/pyglotaran/commit/34ad099a55ac7b073c4efd78966fe477e4c8f9fc)
- [🧪 Added unitest for ParameterGroup.get and label nesting of 3](https://github.com/glotaran/pyglotaran/commit/88350ed95609b9baf67de9dafd429701b37949bb)
closes #933
closes #1042
=> 🩹 ParameterGroup.get degrades full_label of nested Parameters with nesting over 2

changelog.md
Just something we forgot in #869
- [🚧📚 Added reference to project PR to changelog](https://github.com/glotaran/pyglotaran/commit/e21412542433f508e5fb67a553231442e1c66fd0)
=> 🚧📚 Add reference to project PR to changelog

.sourcery.yaml
Looks like sourcery AI won't refactor branches when the github section is in the config.
My guess is that `sourcery_branch: sourcery/{base_branch}` isn't handled gracefully, when not triggered by a webhook (`KeyError` ?).
- [🩹 Remove github section in sourcery config due to bug in sourcery-ai](https://github.com/glotaran/pyglotaran-extras/commit/362b2259505cbc45431b3918c95860a6023575b4)
=> 🩹 Remove github section in sourcery config due to bug in sourcery-ai

.github/workflows/CI_CD_actions.yml, .github/workflows/codeowners_validator.yml, .github/workflows/doxygen.yml, .github/workflows/full_benchmark.yml, .github/workflows/integration-tests.yml, .github/workflows/pr_benchmark.yml, requirements_dev.txt
Combines PRs:
- Bump actions/upload-artifact from 2 to 3 #1056
- Bump actions/download-artifact from 2 to 3 #1055
- Bump codecov/codecov-action from 2 to 3 #1054
- Bump mszostok/codeowners-validator from 0.7.1 to 0.7.2 #1053
- Bump pandas from 1.4.1 to 1.4.2 #1052
- Bump rich from 12.0.1 to 12.2.0 #1051
- Bump click from 8.0.4 to 8.1.2 #1039
=> ⬆️ Combined updates

changelog.md, setup.cfg
This bug wasn't cough by the test since the tests import `glotaran.builtin.megacomplexes.clp_guide` which is equivalent to installing the plugin.
When normally using it the error was:
```python
ValueError: Unknown megacomplex type 'clp-guide'. Known megacomplex types are: 
['baseline', 'coherent-artifact', 'damped-oscillation', 'decay', 'decay-parallel', 'decay-sequential', 
'glotaran.builtin.megacomplexes.baseline.baseline_megacomplex.BaselineMegacomplex', 
'glotaran.builtin.megacomplexes.coherent_artifact.coherent_artifact_megacomplex.CoherentArtifactMegacomplex', 
'glotaran.builtin.megacomplexes.damped_oscillation.damped_oscillation_megacomplex.DampedOscillationMegacomplex', 
'glotaran.builtin.megacomplexes.decay.decay_megacomplex.DecayMegacomplex', …
```
=> 🩹 Fix missing installation of clp-guide megacomplex as plugin

changelog.md, glotaran/model/model.py, glotaran/model/test/test_model.py, glotaran/parameter/parameter.py, glotaran/parameter/parameter_group.py, glotaran/parameter/test/test_parameter_group.py, glotaran/project/scheme.py
This change fixes false positive reporting of a `Model` with parameters or `Scheme` as valid when parameters are missing values and default to `np.nan`.
One use case where a user would want missing parameters is in a teaching exercise where students have to fill in missing parameters.
The other use case would be that a user started editing the parameters file but didn't finish and forgot some values.
As a demo you can use [this notebook](https://github.com/ism200/PE2022/blob/3a5173cce2cf417f605a586c62beedb7a1af4e49/BRC-case-study/BRC_VIS-global-case-study-pretty.ipynb).
- [👌 Don't set default parameter value to zero](https://github.com/glotaran/pyglotaran/commit/e725f4b62e89dd54afd46cb7a92cdf36f2a0318e)
- [🧹 Improved typing and exception …
=> 🩹 Show validation problem if parameters are missing values (default: NaN)

.github/workflows/CI_CD_actions.yml, .github/workflows/integration-tests.yml, changelog.md
Same reasoning as for #978 and #1014
- [🚇🧹 Exclude pre-commit bot branch from CI runs on push](https://github.com/glotaran/pyglotaran/commit/8c7b91bc5ea843b5486032b621d6fdbc0031aa6e)
=> 🚇🧹 Exclude  pre-commit bot branch from CI runs on push

README.md, changelog.md
Follow up PR for #1083 since it is easier to get the correct link when the logo is already in the repo.
So check what the frontpage looks like you can look at [this branch on my fork](https://github.com/s-weigand/pyglotaran/tree/add-new-logo-to-readme)
- [🎨 Added new logo to readme](https://github.com/glotaran/pyglotaran/commit/48cf3a699ea60349de3baeb79c7743862256115f)
=> 🎨 Add new logo to readme

README.md, changelog.md, setup.cfg
This will allow installing `pyglotaran` together with `pyglotaran-extras` by calling `pip install pyglotaran[extras]` or `pip install pyglotaran[full]`
- [🚧🔧 Added 'extras' and 'full' extras_require install option](https://github.com/glotaran/pyglotaran/commit/b89da55036965739f098dac7f7a4f3f9b6b24596)
- [📚 Added note to readme about installing pyglotaran with extras](https://github.com/glotaran/pyglotaran/pull/1089/commits/a584d15302d1fec9ad2fae27d125231c94473c52)
=> 🚧🔧 Add 'extras' and 'full' extras_require installation options

changelog.md
This makes the links explicitly named (permanent) instead of iterating over an index which lead to moving links
Ref.: https://myst-parser.readthedocs.io/en/latest/intro.html#cross-referencing
- [📚🚧✨ Added crossreferences to changelog version sections](https://github.com/glotaran/pyglotaran/commit/e0f203b7c90682faf5d9f0d61d08e5c5f7c08121)
- [changelog latest #id1](https://pyglotaran.readthedocs.io/en/latest/changelog.html#id1)
- [changelog 0.5.0 #id1](https://pyglotaran.readthedocs.io/en/v0.5.0/changelog.html#id1)
=> 📚🚧✨ Make changelog linkable (use explicit anchors)

changelog.md, glotaran/__init__.py
Since `0.6.0` got finally released we should use a dev version again.
- [🚧 Changed version from 0.6.0 to 0.7.0.dev0](https://github.com/glotaran/pyglotaran/commit/50c319f3bb9d113d92ca84eb4acb7b5b05c53dae)
- [🚧📚 Added 0.7.0 section boilerplate to the changelog](https://github.com/glotaran/pyglotaran/commit/fd2d21a52cf25f138db46f507d96d0b143a464c9)
=> 🚧 Set version to 0.7.0.dev0

.github/workflows/pr_benchmark.yml, changelog.md
In #1060 we just found that there is an error in the comparison of the last tag and the main branch in the `pr_benchmark` workflow. Instead of comparing the last tag to main, it compares it against the PR HEAD
- [🚇🩹 Fixed release and main comparison using HEAD instead of main](https://github.com/glotaran/pyglotaran/commit/3728a0f104627f9d5167b4a48b4acfda2a862e93)
=> 🚇🩹 Fix wrong comparison in pr_benchmark workflow

.sourcery.yaml, changelog.md
We do not want sourcery to introduce code that isn't compatible with python 3.8, like the [merge syntax added in python 3.9
](https://docs.python.org/3.9/whatsnew/3.9.html#dictionary-merge-update-operators), as it tried to do [here](https://github.com/glotaran/pyglotaran/pull/1078/commits/20474b9e625a1881e79024e176fdc2e676dd36d8#diff-97392e0b8f76dfbef3b4da24549019509f1c3723cf8373c9e23985eea46b0584R31).
[The default python version of sourcery is python 3.9](https://docs.sourcery.ai/Configuration/Project-Settings/)
- [🔧 Set sourcery-ai target python version to 3.8](https://github.com/glotaran/pyglotaran/commit/728bf439585b1b3aebb88c73ebdb090e078fc655)
=> 🔧 Set sourcery-ai target python version to 3.8

.github/workflows/CI_CD_actions.yml, changelog.md
Recently the [manifest-check CI test started to fail](https://github.com/glotaran/pyglotaran/runs/6938429155?check_suite_focus=true), while I don't completely understand what is going on there it seems to be some kind of version mismatch between setuptools and distutils (python builtin) in the CI python env.
Raising the requirement for setuptool to be at least the current version fixes this issue (might also work with a lower version, but `56.0.0` was the one installed in the broken env).
- [🩹🔧 Upgradegrade setuptools to >=62.4.0](https://github.com/glotaran/pyglotaran/commit/3edd7f0e9fe577037533472ea6da958cc1e72527)
- [🔧 Upgrade setuptools in the deploy step just to be on the save side](https://github.com/glotaran/pyglotaran/commit/1b2cc3df72e61891ebf786184dcd29f33f98aaa5)
=> 🚇🩹🔧 Fix manifest check

changelog.md, glotaran/project/result.py, glotaran/project/test/test_result.py
This change makes the markdown rendering of the result in notebooks/ipython less overwhelming by hiding the model in a details tag which can be expanded.
Requested by @ism200 
- [👌🎨 Wrap model section in result markdown in details tag for notebooks](https://github.com/glotaran/pyglotaran/commit/5d6bf3ca5a90446cc547253e3343a2f2127a194a)
- [🧪 Added test for details tag in ipython render but not in call to markdown](https://github.com/glotaran/pyglotaran/pull/1098/commits/08a0eae633883381393db0de24fe5765951ca91f)
=> 👌🎨 Wrap model section in result markdown in details tag for notebooks

changelog.md, glotaran/optimization/optimization_group.py, glotaran/optimization/test/test_multiple_goups.py
This fixes a bug when using multiple `dataset_groups`, where each `OptimizationGroup` (one per `dataset_group`) overwrites previous results from different `dataset_group` with the input data.
- [🧪 Extended test reproducing overwriting existing result dataset](https://github.com/glotaran/pyglotaran/commit/0c416264f30499122d87725c16fef502d5a1a5bb)
- [🩹 Filter datasets in create_result_data.create_result_data to used ones](https://github.com/glotaran/pyglotaran/commit/6ab5280980b1b58f02d810919b013c2cd2725475)
=> 🩹 Fix result data overwritten when using multiple dataset_groups

.github/workflows/doxygen.yml, .github/workflows/pr_benchmark.yml, .github/workflows/pr_benchmark_reaction.yml, changelog.md
GitHub deprecated the usage of `set-output` in favor of using the environment file located at `$GITHUB_OUTPUT`.
The old syntax already gives warnings and will be switched off 31st May 2023.
This change makes the CI more future proof.
Ref.: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- [♻️🚇 Use GITHUB_OUTPUT instead of set-output in github actions](https://github.com/glotaran/pyglotaran/pull/1166/commits/0395bcce1b1f895a3b59d4509a9b000bb04fe115)
- [📚🩹 Fixed input description for doxygen workflow](https://github.com/glotaran/pyglotaran/pull/1166/commits/a69fe7504b0104987acd701f2837a1faa41789f8)
=> ♻️🚇 Use GITHUB_OUTPUT instead of set-output in github actions

changelog.md, requirements_dev.txt
While setting up a new local environment for pyglotaran I found that the runtime dependency `odfpy` had no pinned version in `requirements_dev.txt`.
- [🚧 Added pinned version of odfpy to requirements_dev.txt](https://github.com/glotaran/pyglotaran/commit/2cc6ee7c0631a0b8ea69a8d0a338865d06465daa)
=> 🚧 Add pinned version of odfpy to requirements_dev.txt

changelog.md, glotaran/deprecation/deprecation_utils.py, glotaran/deprecation/modules/test/test_changed_imports.py, glotaran/deprecation/test/test_deprecation_utils.py, glotaran/model/model.py, glotaran/optimization/data_provider.py, glotaran/optimization/matrix_provider.py, glotaran/optimization/optimization_history.py, glotaran/optimization/test/models.py, glotaran/parameter/parameter_history.py, glotaran/parameter/test/test_parameter.py, glotaran/plugin_system/base_registry.py, glotaran/plugin_system/data_io_registration.py, glotaran/plugin_system/project_io_registration.py, glotaran/plugin_system/test/test_base_registry.py, glotaran/plugin_system/test/test_data_io_registration.py, glotaran/plugin_system/test/test_project_io_registration.py, glotaran/project/generators/test/test_genenerate_decay_model.py, glotaran/project/project.py, glotaran/project/test/test_dataclass_helpers.py, glotaran/project/test/test_project.py, glotaran/utils/sanitize.py, setup.cfg
Since #1135 improved the static type checking a lot we can remove many `# type: ignore` which aren't needed anymore.
- [🔧👌 Mypy Warn on unused type ignore and config](https://github.com/glotaran/pyglotaran/commit/54c89f50972b076f8fd29ea118f4d93f0e01a255)
- [🧹 Removed unused type:ignore](https://github.com/glotaran/pyglotaran/commit/8abfb232f0d8564e00ff5f075a69380a16c17c66)
=> 🧹 Remove unused 'type: ignore'

.pre-commit-config.yaml, benchmark/benchmarks/unit/analysis/bench_optimize.py, changelog.md, glotaran/__init__.py, glotaran/builtin/io/__init__.py, glotaran/builtin/io/netCDF/__init__.py, glotaran/builtin/io/netCDF/netCDF.py, glotaran/builtin/io/sdt/__init__.py, glotaran/builtin/io/sdt/sdt_file_reader.py, glotaran/builtin/io/yml/__init__.py, glotaran/builtin/io/yml/utils.py, glotaran/builtin/io/yml/yml.py, glotaran/builtin/megacomplexes/coherent_artifact/test/test_coherent_artifact.py, glotaran/builtin/megacomplexes/decay/test/test_decay_megacomplex.py, glotaran/io/__init__.py, glotaran/io/interface.py, glotaran/io/prepare_dataset.py, glotaran/model/model.py, glotaran/testing/simulated_data/sequential_spectral_decay.py, glotaran/typing/protocols.py, pyproject.toml, setup.cfg, tox.ini
Changed the `mypy` and `flake8-docs` pre-commit hooks to be opt out instead of opt in and fixed some docstring and typing issues along the way.
- [🔧⌨️ Made mypy optout instead of opt in and fixed some typing issues](https://github.com/glotaran/pyglotaran/commit/aeb4de0db06226c365c5f73adfdac1bcd94a8b61)
- [🔧👌 Moved mypy config from setup.cfg to pyproject.toml](https://github.com/glotaran/pyglotaran/commit/1935679ceeac4af2d270bc4974848726180511ae)
- [🔧👌 Made docstring linter opt out instead of opt in](https://github.com/glotaran/pyglotaran/commit/f1560a35f6cb0e18734ba982136c1a73d0148bd3)
- [🩹 Fix yesqa by moving count from the config to the hook args](https://github.com/glotaran/pyglotaran/commit/ec502da984b12668d4bbff17f232b1cbfd27462b)
closes #1001
=> 🔧 Make mypy and doc string linters opt out instead of opt in

.github/workflows/pr_benchmark.yml, .github/workflows/pr_benchmark_reaction.yml, changelog.md
This PR fixes the broken PR benchmark comments.
Since [`pr_benchmark_reaction.yml` workflow runs on ` workflow_run`](https://github.com/glotaran/pyglotaran/blob/8116af0e60c63349cafb309aeac631f64cf7fa8a/.github/workflows/pr_benchmark_reaction.yml#L6) it never uses the workflow from the PR itself but from the default branch this is why this error wasn't discovered in #1166 which introduced the chance to environment files.
For this PR I tested it on my for by making the virtually identical (at least what concerns the benchmark comment) branch [fix-PR-benchmark-comment](https://github.com/s-weigand/pyglotaran/commit/35b1f2dfb62c85644f5554a8e6ed8f0ce995c93e) the default branch and testing with a [dummy PR](https://github.com/s-weigand/pyglotaran/pull/89).
The commit …
=> 🩹🚇 Fix PR Benchmark comments

glotaran/builtin/megacomplexes/spectral/test/test_spectral_model.py
Fixes division by zero warnings.
- Set spectral_axis_scale to 1
- Remove redundant parameter from spectral_parameters
- Changed spectral parameters to be relevant to simulated spectral window
- Added hints about change of rtol to atol
- Added hint about adding noise to test
- 🩹 Correct parameters in test_spectral_model
closes #1181
=> 🩹 Fixes to test_spectral_model

changelog.md, glotaran/optimization/data_provider.py
Fixes issue where when using more than 32 datasets the xarray operation .str.join across the dataset dimension would crash.
- 🩹 Fix for crash when doing an optimization using more than 30 datasets
closes #1183
=> 🩹Fix for crash when running optimization with more than 30 datasets

changelog.md, glotaran/optimization/matrix_provider.py
This PR is meant to fix an issue with grouping inadvertently introduced in PR #1175 
- 🩹 Fix the matrix provider alignment/reduction ('grouping') issues introduced in #1175 (#1190)
closes #XXXX
=> 🩹 Fix matrix provider

changelog.md, glotaran/builtin/io/yml/test/test_save_result.py, glotaran/builtin/io/yml/test/test_save_scheme.py, glotaran/builtin/io/yml/yml.py, glotaran/utils/io.py, glotaran/utils/test/test_io.py
This fixes a bug when saving a result as yaml using a relative path, which added wrong file paths and broke loading the result. 
We didn't discover this bug since all the examples use absolute paths.
To reproduce the issue use the following code snipped (e.g. in a notebook)
```python
from glotaran.optimization.optimize import optimize
from glotaran.testing.simulated_data.parallel_spectral_decay import SCHEME
result = optimize(SCHEME)
result.save("results/result.yaml")
```
This generates the following files:
```
results
├── dataset_1.nc
├── initial_parameters.csv
├── model.yml
├── optimization_history.csv
├── optimized_parameters.csv
├── parameter_history.csv
├── result.md
├── result.yaml
└── scheme.yml
```
On main the paths pointing to other files used `result.yaml` and `scheme.yml` use a …
=> 🩹 Fix yaml result saving with relative paths

changelog.md, glotaran/model/item.py, glotaran/model/model.py, glotaran/model/test/expected_model_markdown.md, glotaran/model/test/test_model.py
This fixes model markdown render for items without label (e.g. weight) due to invalid markdown.
The problem was that the default value when the `label` is missing was `""` which resulted in `****` meaning `hline` and breaking the indented code below, using `"&nbsp;"` as default fixes this problem.
I used this opportunity to extract the expected markdown code to a markdown file which allows previewing it in your editor (if it supports markdown preview) and early catch reader errors, changing the markdown syntax in the way [prettier](https://prettier.io/) would format it (editor autoformat kicked in and why not 😅).
```md
* ****
* *Datasets*: ['d1', 'd2']
* *Global Interval*: (1, 4)
* *Model Interval*: (2, 3)
* *Value*: 5.4
```
<details>
<summary>Rendered</summary>
* ****
* *Datasets*: …
=> 🩹 Fix model markdown render for items without label

changelog.md, glotaran/project/project.py, glotaran/project/project_registry.py, glotaran/project/project_result_registry.py, glotaran/project/test/test_project.py
This PR fixes an issue with using project due to partial matching of file names where the wrong file was loaded if it started with the same string as the intended file, but is higher in the string sorting order.
E.g. if you had 2 files `model.yml` and `model-target.yml` in your projects `models` folder and would call `project.load_model("model")` it would load `model-target.yml`.
In addition, some code duplications were removed and error messages for missing files were improved.
- [🧪 Changed project tests to fail due to partial filename matching](https://github.com/glotaran/pyglotaran/commit/ba956d6c7c556bf5b0b32ba07ed9594f576980b2)
(Note: The "bad" files were added to the markdown repr string since it should show all files)
- [🩹 Fix file …
=> 🩹 Fix wrong file loading due to partial filename matching in Project

changelog.md, glotaran/plugin_system/data_io_registration.py, glotaran/plugin_system/io_plugin_utils.py, glotaran/plugin_system/test/test_data_io_registration.py, glotaran/plugin_system/test/test_project_io_registration.py, glotaran/project/project_data_registry.py, glotaran/project/test/test_project.py
This fixes a bug in `Project.import_data` causing a `ValueError` when using a relative path and the directory of the script is not the current working directory.
This is the case in editors when the script is not at the folder root or when calling it from python (e.g. `python myproject/script1.py`)
In addition, I improved the saving functionality of the plugin system to create parent folders for files.
Before that trying to save a file to a location with a nonexisting parent folder caused a massive traceback from the undelaying writer implementation.
<details>
<summary>
Example traceback
</summary>
```python
save_dataset(result.data["dataset1"], "nonexisting_folder/dataset1.nc")
```
```python
---------------------------------------------------------------------------
KeyError …
```
=> 🩹 Fix `Project.import_data` path resolving for different script and cwd

changelog.md, glotaran/cli/main.py, glotaran/cli/test/test_cli.py, pyproject.toml
This PR adds a deprecation notice to the CLI whenever it is invoked (init of `CLI`).
- [🗑️ Deprecate CLI](https://github.com/glotaran/pyglotaran/commit/9d36ee50e2919daa88db254df69391438e863a5b)
closes #1227
=> 🗑️ Deprecate CLI

changelog.md, glotaran/builtin/io/yml/test/test_save_result.py, glotaran/builtin/io/yml/yml.py, glotaran/plugin_system/data_io_registration.py, glotaran/plugin_system/io_plugin_utils.py, glotaran/plugin_system/project_io_registration.py, glotaran/plugin_system/test/test_io_plugin_utils.py
Since the yaml plugin is currently the only plugin that allows for full result saving and saves a superset (additional `model.yml`, `scheme.yml` and `result.yml`) of the files saved by `legacy` (due to deprecation in `0.8.0` ) it is reasonable to make it the default.
This allows users to omit the now superfluous `result.yml` when saving a result.
**Note:**
Changing the default of ``load_result`` is also save since the plugins ``legacy``|``folder`` did not and do not have a ``load_result`` method.
Now you can use:
```python
save_result(result, result_folder)
```
or
```python
result.save(result_folder)
```
Thanks to @joernweissenborn for bringing this to my attention again.
- [👌 Allow passing folder to yaml save_result plugin in addition to …
=> 👌 Make yaml the default plugin when passing a folder to save_result and load_result

changelog.md, glotaran/project/project.py, glotaran/project/project_data_registry.py, glotaran/project/project_model_registry.py, glotaran/project/project_parameter_registry.py, glotaran/project/project_registry.py, glotaran/project/project_result_registry.py, glotaran/project/test/test_project.py
This change allows using of files in subfolders for (parameters, models and data) with the project API. 
It handles the ambiguity of files (same file name different extensions next to each other) gracefully by creating unique names and warning the user.
- [♻️ Factor out item name to be an init parameter](https://github.com/glotaran/pyglotaran/commit/0b5e545e99f109e4fca47593bbab6404ee82e10c)
- [✨ Allow usage of subfolders in project parameters, models and data](https://github.com/glotaran/pyglotaran/commit/2ca3ddcc221a3b6c2d10332d53f5ccd5e8af18fd)
- 👌 Gracefully handle and warn the user about ambiguity due to files with the same name but different extensions next to each other
- [♻️ Sort file paths when globbing to make errors deterministic](https://github.com/glotaran/pyglotaran/commit/fb4 …
=> ✨ Allow usage of subfolders in project API for parameters, models and data

changelog.md, glotaran/project/project.py, glotaran/project/project_data_registry.py, glotaran/project/test/test_project.py
This makes data importing with the project API more flexible by allowing direct import from `xarray.Dataset` or `xarray.DataArray`.
```py
from glotaran.project import Project
project = Project.open("my_project")
my_dataset = my_custom_load_function("dataset.foobar")
project.import_data(my_dataset , name="my_dataset ")
```
- [✨ Allow import of xarray objects in project API import_data](https://github.com/glotaran/pyglotaran/commit/909c7db43ce6318ea99237903143c0321a55ffb0)
=> ✨ Allow import of xarray objects in project API import_data

.gitignore, changelog.md, glotaran/deprecation/modules/test/test_project_project.py, glotaran/plugin_system/io_plugin_utils.py, glotaran/plugin_system/test/test_io_plugin_utils.py, glotaran/project/project.py, glotaran/project/project_data_registry.py, glotaran/project/project_registry.py, glotaran/project/test/test_project.py, glotaran/utils/ipython.py, glotaran/utils/test/test_ipython.py
While rewriting the quickstart guide to use the project  API I found a number of refinements that needed to be done so @joernweissenborn vision of a single import can be realized (at least for the quickstart).
The deprecation of model and parameters generators in the project API (for good) was in agreement with @joernweissenborn since they lack ease of use and don't fit in a notebook workflow (our currently recommended UI).
See #1241 for the new usage.
- [👌 Improved Project markdown repr](https://github.com/glotaran/pyglotaran/commit/58b0611e2879fe0627afd1910f68f3dcbba691ea)
- [👌 Made Project.optimize return the current result for usage convenience](https://github.com/glotaran/pyglotaran/commit/c05e646c0a28f3d0828b4b49f7e518b55da222a1)
- [🧹 Add quickstart output files to …
=> 👌 Refine project API

docs/environment.yml, glotaran/project/result.py, readthedocs.yml
This is just a hack for the docs to render properly with the markdown repr of `Result`.
See current [docs on main](https://pyglotaran.readthedocs.io/en/latest/notebooks/quickstart/quickstart.html) (will be different in the future when looking back at this PR) and [the build for this PR](https://pyglotaran--1244.org.readthedocs.build/en/1244/notebooks/quickstart/quickstart.html) (might be deleted) 
<details>
<summary>
Down the rabbit hole
</summary>
The problem is the markdown repr of the Result and our notebook docs plugin (nbsphinx) using pandoc to transform markdown to  reST as the intermediate format that sphinx can then picked up by sphinx (doc building framework) to create html, latex ...
The markdown repr of Result looks something like this
```
TABLE<in md>
<details>
...
</details> …
```
=> 📚🩹 Fix rendering of Result with nbsphinx (workaround)

changelog.md, glotaran/builtin/megacomplexes/test/test_spectral_decay_full_model.py, glotaran/deprecation/modules/test/test_project_result.py, glotaran/optimization/matrix_provider.py, glotaran/optimization/optimization_group.py, glotaran/optimization/optimizer.py, glotaran/optimization/test/suites.py, glotaran/optimization/test/test_constraints.py, glotaran/optimization/test/test_matrix_provider.py, glotaran/optimization/test/test_penalties.py, glotaran/optimization/test/test_relations.py, glotaran/project/result.py
This change adds `number_of_clps` to the `MatrixProvider`'s, `OptimizationGroup` and the `Result` classes.
When degrees of freedom are calculated the `number_of_clps` are subtracted.
In addition `number_of_data_points` was deprecated from `Result` since we found that what we actually report is `number_of_residuals` which is the more interesting value anyway since it also contains the penalties.
So following a discussion @ism200 we won't report the number of datapoints anymore.
- [🗑️ Deprecated Result.number_of_data_points in favor of Result.number_of_residuals](https://github.com/glotaran/pyglotaran/commit/549dad60c68c0ee58760353a40f611b573669c43)
- [✨ Add number_of_clps property to MatrixProvider's and OptimizationGroup](https://github.com/glotaran/pyglotaran/commit/7efbd5c931605cecef22be …
=> 🩹 Add number_of_clps to result and correct degrees_of_freedom calculation

.gitignore, flake.lock, flake.nix, pyproject.toml
This enables user with `nix` installed to work on pyglotaran. The flake creates a shell with python 3.10 and virtualenv installed and installs all dependencies on first creation.
=> Dev: Add flake.nix for creating dev shells with nix.

changelog.md, glotaran/builtin/io/yml/yml.py
This change allows the loading of results with `load_result` created before merging #1249 which deprecated `number_of_data_points` and removed it from the init.
- [🩹 Fix loading of old results containing number_of_data_points](https://github.com/glotaran/pyglotaran/commit/ed22b135dcabba4c0b9adf6d52c2e9b4ec993f24)
=> 🩹 Fix loading of old results containing number_of_data_points

changelog.md, glotaran/project/project.py, glotaran/project/project_data_registry.py, glotaran/project/test/test_project.py
This PR improves the data handling of the Project API in notebook workflows.
Since notebooks are often executed as a whole (`Run All`) the default of `ignore_existing=False` in `project.import_data` leads to using `ignore_existing=True` each time calling it in an actual case study, which makes the code less readable and adds a lot of redundancy and a default of `ignore_existing=True` is more sensible (IMHO `ignore_existing=False` only makes sense in a CLI or GUI context). 
Having to import each dataset one by one also clutters the code quite a lot.
```py
project.import_data("measured_data/Npq2_220219_800target3fasea.ascii", dataset_name="TA")
project.import_data(guide_s1, dataset_name="guide_s1")
project.import_data(guide_s2, dataset_name="guide_s2")
project.import_data(guide_s3, …
```
=> 👌 Improve Project API data handling

glotaran/io/preprocessor/__init__.py, glotaran/io/preprocessor/pipeline.py, glotaran/io/preprocessor/preprocessor.py, glotaran/io/preprocessor/test/test_preprocessor.py, requirements_dev.txt, setup.cfg
Adds a (chainable) PreProcessingPipeline with (initial) support for CorrectBaselineAverage and CorrectBaselineValue.
=> Feature: Add dataprocessor.

changelog.md, glotaran/builtin/io/yml/yml.py, glotaran/deprecation/modules/test/test_project_result.py, glotaran/optimization/optimizer.py, glotaran/project/result.py
This change makes it more clear that `number_of_parameters` always meant `number_of_free_parameters`.
- [🗑️ Deprecate Result.number_of_parameters in favor of Result.number_of_free_parameters](https://github.com/glotaran/pyglotaran/commit/a6b66a4cb6cd77c008bcc0a1b01b0ea27d967ff0)
=> 🗑️ Deprecate Result.number_of_parameters in favor of Result.number_of_free_parameters

changelog.md, glotaran/io/preprocessor/pipeline.py, glotaran/io/preprocessor/test/test_preprocessor.py
This changes the behavior of methods on `PreProcessingPipeline ` to be closer to how `pandas` or `xarray` work (object creation instead of in place mutation), which makes it more intuitive and prevents accidental state changes in the pipeline (e.g. executing a cell in a notebook that does not include the instantiation multiple times).
- [👌 Make PreProcessingPipeline methods return a new instance](https://github.com/glotaran/pyglotaran/commit/85766610a17123b5ba890cca67e11725629c8e27)
=> 👌 Make PreProcessingPipeline methods return a new instance

changelog.md, docs/requirements.txt, docs/source/conf.py
Currently, the search functionality in our docs hangs indefinitely.
The error you get in the dev tools console is 
```js
Uncaught ReferenceError: jQuery is not defined
```
This relates to a change in the rtd theme and how to use it (old config).
- [🩹📚 Fix search in docs](https://github.com/glotaran/pyglotaran/commit/cc534bd8381f7a9046cc2dd90f6890730f6993e2)
=> 🩹📚 Fix search in docs

.github/workflows/CI_CD_actions.yml, CONTRIBUTING.rst, changelog.md, docs/source/installation.rst, requirements_dev.txt, setup.cfg
Since python 3.11 came out some time ago we should also see we can already support it (mostly dependency issue).
- ✨🚇 Added python 3.11 CI tests
=> ✨🚇 Add official python 3.11 support

.github/stale.yml
Automatically close stale Issues and Pull Requests that tend to accumulate during a project. 
As suggested here: https://github.com/glotaran/pyglotaran/issues/749#issuecomment-921319429 
> After a period of inactivity, a label will be applied to mark an issue as stale, and optionally post a comment to notify contributors that the Issue or Pull Request will be closed.
> 
> If the Issue or Pull Request is updated, or anyone comments, then the stale label is removed.
> 
> If no more activity occurs, the Issue or Pull Request will be automatically closed.
Ref: https://github.com/marketplace/stale
closes: #749
=> 🧰 Stale bot

.github/workflows/release-validataion.yml
I added a pipeline that automatically creates a release on [pyglotaran-validation](https://github.com/glotaran/pyglotaran-validation) and [pyglotaran-examples](https://github.com/glotaran/pyglotaran-examples) when a release for pyglotaran is created.
For the examples, it also triggers a pipeline in that repo uploading comparison results.
This way each pyglotaran release will automatically become reproducible validation wise.
I tested it on my fork and [this pyglotaran release on my fork](https://github.com/s-weigand/pyglotaran/releases/tag/vFinalAutoreleaseTest) created those releases on [validation fork](https://github.com/s-weigand/pyglotaran-validation/releases/tag/vFinalAutoreleaseTest) and [examples fork](https://github.com/s-weigand/pyglotaran-examples/releases).
- [🚀🚇 Add pileline …
=> 🚀🚇 Add pipeline to release examples and validation on release

changelog.md, glotaran/optimization/optimizer.py, glotaran/parameter/parameters.py
Correctly report standard error in the case that non_negative contraint is used.
- 👌Improve reporting of standard error in case of non_negative constraint in the parameter
=> 🩹 Transform standard error if parameter has non_negative constraint

requirements_dev.txt
Combined dependency updates
- [Bump pydantic from 1.10.9 to 1.10.11](https://github.com/glotaran/pyglotaran/commit/71b736c06cf47d67b8fb0af6e762fc98b620d44f)
- [Bump xarray from 2023.6.0 to 2023.7.0](https://github.com/glotaran/pyglotaran/commit/c7c1eaec078254f10f6c9d55be02470c50a2d4ee)
- [Bump click from 8.1.5 to 8.1.6](https://github.com/glotaran/pyglotaran/commit/ee102dc2bb1634d53f07d6a04c8d33bcacb41f03)
- [Bump asteval from 0.9.30 to 0.9.31](https://github.com/glotaran/pyglotaran/commit/4258c78107ae4edddb05b5fc3c9aef84b32b996e)
- [Bump numpy from 1.24.3 to 1.24.4](https://github.com/glotaran/pyglotaran/commit/a525ea263b19fdaeb48a4e6f5dcf723490542e26)
closes #1332 
closes #1330 
closes #1331  
closes #1329
closes #1328
=> ⬆️ Combined dependency updates

changelog.md, glotaran/__init__.py
After the `0.7.1` release we can go back to the `0.8.0` development
- [🚧 Back to 0.8.0 development](https://github.com/glotaran/pyglotaran/commit/83889cefbe1b7b8489c6dd35de7b101425a42e3d)
=> 🚧 Back to 0.8.0 development

changelog.md, requirements_dev.txt, setup.cfg
This pull request removes the unused dependency `rich` from the `requirements_dev.txt` and `setup.cfg` configuration files. The removal of this dependency is a finding from ongoing research aimed at identifying and eliminating code bloat within software projects.
The `rich` library was introduced in the project in 2f1afe78 for its use in `glotaran/testing/test/test_model_generators.py`. However, the relevant file was removed on 09de6b2, rendering the dependency unnecessary. Despite its removal from the source code, `rich` remained listed as a requirement in the project's configuration files. Removing this unused dependency  reduces the overall footprint of the application, mitigating potential security risks, and simplifying the dependency management process.
- Removed the `rich` …
=> 🧹 Remove unused dependency: rich

docs/requirements.txt, glotaran/builtin/io/yml/utils.py, requirements_dev.txt
Combining runtime updates for:
- numda
- pandas
- pydantic
- xarray
- sdtfile
- ruamel-yaml
And an update to docs/requirements.txt for:
- pillow
=> ⬆️ Combi update

glotaran/optimization/test/test_objective.py, glotaran/project/scheme.py
Adds dry run to optimze
Fixes a pytest issue
=> Various improvements

glotaran/__init__.py, glotaran/plugin_system/base_registry.py
This fixes the deprecation warning caused by `load_plugins` we see in the tests
```py
glotaran/plugin_system/base_registry.py:130
glotaran/plugin_system/base_registry.py:130
glotaran/plugin_system/base_registry.py:130
glotaran/plugin_system/base_registry.py:130
glotaran/plugin_system/base_registry.py:130
glotaran/plugin_system/base_registry.py:130
/home/runner/work/pyglotaran/pyglotaran/glotaran/plugin_system/base_registry.py:130: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
for entry_points in [entry_points[p] for p in plugin_names]:  # type:ignore[assignment]
```
=> 🩹 Fix load_plugins deprecation warning

glotaran/optimization/data.py
Tested with freshly ported ex_two_datasets example
=> 🩹 Fix dataset weights

glotaran/builtin/elements/baseline/element.py, glotaran/builtin/elements/clp_guide/element.py, glotaran/builtin/elements/coherent_artifact/element.py, glotaran/builtin/elements/damped_oscillation/element.py, glotaran/builtin/elements/kinetic/element.py, glotaran/builtin/elements/spectral/element.py, glotaran/model/data_model.py, glotaran/model/element.py, glotaran/model/test/test_data_model.py
With pydantic 2 we had crashes when calling `.model_json_schema()` e.g.
```py
from glotaran.project import Scheme
Scheme.model_json_schema()
```
The main reason for this was pydatic failure to serialize `data_model_type` to json since the value is a class.
~~This can all be prevented by making internal only fields "private" (leading `_`) so they get excluded from the schema since we don't want users to put values for them anyway.~~
As @joernweissenborn  noted properly typing the fields with `ClassVar` those variables will also not be considered for the schema.
=> 🩹 Fix schema generation by making private attributes private

glotaran/builtin/items/activation/gaussian.py
The optimizer would crash
When setting the values in the model scheme from a constant to a parameter, the optimizer would crash with "Cannot determine Numba type of <class 'glotaran.parameter.parameter.Parameter'> " as it tried to use the parameter as a numeric value. Ultimately numba would complain as that's where the value would be first used.
Specifically: `"glotaran\builtin\elements\kinetic\matrix.py", line 27`
<sub>Note: This PR doesn't add a unit test (yet), but that should be added at the level of the optimizer since the element tests themselves work only with numeric definitions.</sub>
=> 🩹Fix for when the backsweep is a parameter rather than constant

glotaran/builtin/elements/kinetic/element.py, glotaran/builtin/elements/kinetic/matrix.py, glotaran/builtin/items/activation/gaussian.py, tests/builtin/items/activation/test_activation.py
Just a small additional clean-up after #1422 to get rid of the `backsweep` boolean flag, which is a residual of the [`< 0.8` model syntax when we had this as user input](https://github.com/glotaran/pyglotaran-examples/blob/dc7436798fdc44e5b8fc74c20e9afe452f8e10ee/pyglotaran_examples/study_fluorescence/models/model-target.yaml#L31).
- [🧹 Remove redundant backsweep flag from GaussianActivationParameters](https://github.com/glotaran/pyglotaran/commit/438a7e9a3fa9bf0874dd5c76e7b2958838c14962)
=> 🧹 Remove redundant backsweep flag from GaussianActivationParameters

.pre-commit-config.yaml, .ruff-notebooks.toml, .ruff.toml, glotaran/model/element.py, glotaran/model/item.py, glotaran/project/library.py, tests/deprecation/test_deprecation_utils.py, tests/parameter/test_parameter.py, tests/parameter/test_parameters_rendering.py
By using the plugin registry instead of looking up inheritance we can ensure that only elements that were explicitly added are valid types (e.g. `ExtendableElement` is not instantiable by itself and should not be part of `LibraryType`).
- [🧹 Use element plugin registry to define LibraryType](https://github.com/glotaran/pyglotaran/commit/becc4b6a88232169950f32a05674eb769b967182)
- [🧹 Remove InternalMockElement](https://github.com/glotaran/pyglotaran/commit/fa8b6775b939f12dc03bf5b4d44e9afc4f8968ad)
- [🧰⬆️ Update pre-commit config](https://github.com/glotaran/pyglotaran/commit/28e405141889baac9b0378b3ffb97838223a707a)
=> 🧹 Use element plugin registry to define LibraryType

glotaran/builtin/io/pandas/csv.py, glotaran/builtin/io/pandas/xlsx.py, glotaran/utils/io.py, requirements_dev.txt
Combined update of python dependencies
- [Bump pandas from 2.1.4 to 2.2.1](https://github.com/glotaran/pyglotaran/commit/24e9878d6b5094265e98f5673665de261034e24f)
- [🩹🗑️ Fix pandas deprecations](https://github.com/glotaran/pyglotaran/commit/db8fab4752bdc70c653f10ff6c0b4ff1ea2da28d)
- [Bump numba from 0.58.1 to 0.59.0](https://github.com/glotaran/pyglotaran/commit/a6a592b2e4cbd4241609fe6db450dcf902464ead)
- [Bump numpy from 1.26.2 to 1.26.4](https://github.com/glotaran/pyglotaran/commit/a477445bbb1a2003c6a0c2a954b9023c9a2b3f4a)
- [Bump asteval from 0.9.31 to 0.9.32](https://github.com/glotaran/pyglotaran/commit/3b18dc4d3d71ad60ce02447675c939fa82d2c991)
- [Bump attrs from 23.1.0 to 23.2.0](https://github.com/glotaran/pyglotaran/commit/b4d24126b97e54f0aa5087379c97846e5d46dc4c)
- [Bump …
=> ⬆️ Combined python updates

.github/workflows/CI_CD_actions.yml, changelog.md, glotaran/plugin_system/base_registry.py, setup.cfg
[Numba 0.59.0 added python 3.12 support](https://github.com/numba/numba/releases/tag/0.59.0), which means so can we.
- [✨ Add official Python 3.12 support](https://github.com/glotaran/pyglotaran/commit/2c993be287b3a8ab8c16668bde0a478b5431d8c8)
=> ✨ Add official Python 3.12 support

.github/workflows/integration-tests.yml
Switch back to `GeekyEggo/delete-artifact` after the permission issue fix was released.
- [🚇🧹 Switch back to GeekyEggo/delete-artifact](https://github.com/glotaran/pyglotaran-extras/commit/e8fd9533ecf2446edd817132d6f0b18fa0e30055)
=> 🚇🧹 Switch back to GeekyEggo/delete-artifact

flake.lock, flake.nix, glotaran/optimization/matrix.py, glotaran/optimization/objective.py, glotaran/plugin_system/project_io_registration.py, tests/optimization/library.py, tests/optimization/test_relations_and_constraints.py
=> Staging fix relations

.github/workflows/integration-tests.yml
With this change the integration tests used the examples ported to the staging syntax (see https://github.com/glotaran/pyglotaran-examples/pull/101 and https://github.com/glotaran/pyglotaran-examples/pull/102)
- [🚇 Use pyglotaran-examples@staging_rewrite for CI integration tests](https://github.com/glotaran/pyglotaran/commit/d874b863edd7c95686787ab755beddca0dee09af)
=> 🚇 Use pyglotaran-examples@staging_rewrite for CI integration tests

tests/model/test_item.py
Rather than testing upstream functionality for an exact match, we should test that the schema we generate for a spec file validate correctly. 
The problem with testing exact schema matching is that it is too tightly coupled to the exact syntax of the schema, even so they might be functionally equivalent, leading to failing unit tests due to upstream schema refinements.
See [this recent CI fail with unrelated changes](https://github.com/glotaran/pyglotaran/actions/runs/9428522912/job/25973949081?pr=1461):
```py
Omitting 5 identical items, use -vv to show
Differing items:
{'properties': {'type': {'const': None, 'enum': [None], 'title': 'Type', 'type': 'null'}}} != {'properties': {'type': {'const': None, 'title': 'Type'}}}
Full diff:
{
'additionalProperties': False,
'description': 'This is …
```
=> 🧪🧹 Remove test of upstream schema creation functionality

.github/workflows/integration-tests.yml
Changing the `glotaran/pyglotaran-examples` to use notebooks broke the integration test pipeline because the output variable was changed from `plots-path` to `notebook-path`.
- [🩹🚇 Fix integration test pipeline](https://github.com/glotaran/pyglotaran/commit/62caaebaf0bdc6692410316c9039238e2da983da)
=> 🩹🚇 Fix integration test pipeline

.github/dependabot.yml
This PR improves the efficiency of `dependabot` updates by grouping them instead of open PRs for each dependency. It also deactivates autorebase to not unnecessarily spam the CI (we can still use `@dependabot rebase` or local rebase and push if needed).
It also activates `dependabot` for the `staging branch`.
- [🚧🚇👌 Use dependabot groups to reduce the amount of PRs](https://github.com/glotaran/pyglotaran/commit/d01c493fb7a8df1871bc42c2f298572f6fd30e03)
- [🚧🚇👌 Disable dependabot auto rebase to reduce CI spam](https://github.com/glotaran/pyglotaran/commit/7efc302a23aea6c4180c25c926b2b0d34e99ea34)
- [🚧🚇👌 Activate dependabot for staging](https://github.com/glotaran/pyglotaran/commit/49d77b3dcde6bd35aef6e0066f57db6eab158f14)
=> 🚧🚇👌 Improve dependabot config

glotaran/optimization/objective.py, glotaran/optimization/optimization.py, glotaran/optimization/result.py, tests/optimization/test_objective.py
Fixes #1474
- This adds `additional_penalty` to the result object and renames `nr_clp` back to `number_of_clps`.
- Correct degrees_of_freedom calculation.
=> Fix 1474 - add fields to result object - correct calculation of number of clps.

glotaran/model/item.py, tests/model/test_item.py
Add the dependent parameters after its dependencies.
Parameters involved in a relation (parameter expression) should be added before the parameter that declares a dependency on them.
- 🩹Fix order of parameters involved in parameters expresssion
closes #1499
=> 🩹Fix order of parameters involved in parameters expresssion

changelog.md, glotaran/builtin/megacomplexes/damped_oscillation/damped_oscillation_megacomplex.py, glotaran/builtin/megacomplexes/damped_oscillation/test/test_doas_model.py
During the review of #1510 we found an inherited bug from the DOAS megacomplex where a faulty user definition would raise an `AttributeError` when the `ItemIssue` get converted to a string that is show to users.
- [🧪 Add failing test reproducing the AttributeError validating a bad DOAS user definition](https://github.com/glotaran/pyglotaran/commit/5409d4d163405d68c4b09036fc64d0643d3fc58f)
- [🩹 Fix AttributeError validating bad DOAS user definition](https://github.com/glotaran/pyglotaran/commit/1f697b98a2c703cc46ec04465f529980d3695e48)
=> 🩹 Fix AttributeError validating bad DOAS user definition

.pre-commit-config.yaml
Fixes 2 issues with faulty pre-commit configuration
- error when initializing clean pre-commit environment due to yanking of types-all
- fail in interrogate pipeline on missing pkg_resources in some environments due to interrogate not declaring explicit dependency on setuptools
=> 🧰 Fix pre-commit config issues

glotaran/io/prepare_dataset.py
This should fix an issues with numpy > 2.0.1 and should be backwards compatible.
- In the prepare_dataset function where svd are added we use the .data attribute of the xarrray dataarray to get the numpy array to be used in the calculation.
=> 🩹 Use svd function on raw numpy arrray instead of xarray dataarray

glotaran/io/prepare_dataset.py
Forward port of #1520
- 🩹Fix prepare_dataset's add_svd_to_dataset function by using raw numpy .data array instead of xarray dataarray by to resolve an issue with numpy>2.
=> 🩹 Use .data attribute in add_svd_to_dataset function to fix numpy>2 issue
