- README.md
- setup.py
Hi guys,
i found that the installation of lmfit-varpro from my PR #76  didn't work, but now it does ;)
> Fix lmfit varpro installation

- README.md
Added the badge for the glotaran documentation on read the docs
> Add rtd badge

- CONTRIBUTING.rst
This regards #100 .
Minor change in the installation guide for contributers.
closes #100
> updated installation guide

- docs/installation.rst
Just a small typo fix, no need for an issue i guess.
> fixed some typos in windows workround guide

- .travis.yml
Just a small bug I introduces in #115
> Fixes travis failing

- appveyor.yml
- glotaran/model/parameter.py
- glotaran/model/parameter_group.py
- tox.ini
* Changed ``appveyor.yml`` to only build whees when tests pass
* Fixed flake8 env in ``tox.ini``
* Fixed errors in docstrings which caused tests to fail
**Testing**
Only flake8 fails
closes #117
> Only build win wheels on success

- README.md
* Added badges for travis, appveyor and coveralls
> Add service badges

- docs/Makefile
- setup.py
* Changed Makefile for docs as proposed in #121 
*  Changed required version of ``lmfit-varpro`` to its new current version
closes #121
> Make doc make scripts version sensitiv

- docs/Makefile
* Added change from #122 if forgot to commit so ``cd docs; make api_docs`` works
> Added last commit i forgot on #122

- README.md
* Changed link to credidts in `README.md` from rst style to md style
closes #129
> fixed rst link on README.md

- README.md
- appveyor.yml
- setup.py
* Rencrypted PyPi password from new glotran orgaisation appveyor
* Changed badges to point at master and  new glotran orgaisation appveyor
* Bumped min version for `lmfit-varpro`
* Fixed bug in `appveyor.yml` pointing at my fork of  `lmfit-varpro`
closes #133
> Fix win deploy

- glotaran/models/spectral_temporal/dataset_descriptor.py
- glotaran/models/spectral_temporal/kinetic_matrix.py
- glotaran/models/spectral_temporal/spectral_matrix.py
- glotaran/models/spectral_temporal/spectral_shape.py
- glotaran/models/spectral_temporal/spectral_shape_gaussian.py
- glotaran/specification_parser/model_spec_yaml_kinetic.py
- glotaran/specification_parser/test/test_model_parser_kinetic.py
> Add support for multiple Gaussian #104

- glotaran/fitmodel/fitmodel.py
- setup.py
> Set nan_policy to `omit`

- .coveragerc
- .travis.yml
- appveyor.yml
- tox.ini
* Excluded Tests themself from coverage
* Fixed generation of coverage with Tox
* Fixed generation of coverage with CIs
* Removed lmfit-varpro force installation
closes #138 #139
> Generate correct coverage

- glotaran/data/dataio/file_readers.py
- glotaran/data/dataio/legacy_readers.py
- glotaran/data/dataio/mapper.py
- glotaran/data/dataio/test/test_file_readers.py
- glotaran/data/dataio/test/test_legacy_readers.py
- glotaran/data/datasets/specialized_datasets.py
- glotaran/data/datasets/spectral_temporal_dataset.py
- glotaran/model/model_item.py
- glotaran/plotting/basic_plots.py
- tox.ini
This PR fixes the recent flake8 fails and adds python 3.7 as a default test env to tox.
closes #163
> Fix flake8 errors

- docs/conf.py
- setup.py
Updated setup.py and sphinx documentation used conf.py with changed author ordering to reflect in auto generated documentation.
As the creator of the original (Java based) glotaran software package and the first author of the first glotaran publication [1] I would like to recognize the efforts of Joern Weissenborn (@joernweissenborn) in particular in creating this Python implementation from scratch by listing him first in the author's list. This incarnation of the glotaran software, pyglotaran if you will, also includes a computational core previously only available in the form of the open source R package TIMP [2], so it is fully self contained. This incarnation of the software is the future of glotaran and perhaps even global and target analysis software in general and will eventually …
> Changed author ordering to list Joern as main development lead

- .github/workflows/CI_CD_actions.yml
- requirements_dev.txt
- setup.py
Update github actions to make docs dependent on test
> Update github actions to make docs dependent on test

- .github/workflows/CI_CD_actions.yml
> Update GitHub actions

- glotaran/builtin/models/kinetic_image/kinetic_image_result.py
- glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_matrix.py
- glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py
- glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_result.py
- glotaran/builtin/models/kinetic_spectrum/spectral_irf.py
- glotaran/builtin/models/kinetic_spectrum/test/test_coherent_artifact.py
Part refactor part fixing coherent artifact with dispersion functionality
TODO: increase test coverage
> Moved coherent artifact from kinetic_image to kinetic_spectrum

- .github/workflows/CI_CD_actions.yml
- requirements_dev.txt
- setup.py
> Removed unneeded explicit dependencies

- glotaran/builtin/models/kinetic_image/irf.py
- glotaran/builtin/models/kinetic_image/kinetic_image_matrix.py
> Coherent artifact with dispersion

- README.md
Adds a badge for dependabot to the readme (see #300)
> Add dependabot badge to readme

- LICENSE
- docs/make.bat
- docs/source/conf.py
- glotaran/builtin/file_formats/sdt/sdt_file.py
Updating broken links, also updating http to https where possible.
> Fix broken URLs and improve docs

- glotaran/analysis/matrix_calculation.py
- glotaran/analysis/residual_calculation.py
- glotaran/analysis/simulation.py
- glotaran/builtin/models/doas/doas_matrix.py
- glotaran/builtin/models/kinetic_image/kinetic_image_matrix.py
- glotaran/builtin/models/kinetic_image/kinetic_image_result.py
- glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py
- glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_result.py
- glotaran/builtin/models/kinetic_spectrum/spectral_constraints.py
- glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py
- glotaran/builtin/models/kinetic_spectrum/spectral_relations.py
- glotaran/cli/commands/explore.py
- glotaran/cli/commands/optimize.py
- glotaran/model/model.py
- glotaran/parameter/parameter_group.py
address recent flake8 errors
Change of type hints 'KineticModel' to 'KineticImageModel' or 'KineticSpectrumModel', which should affect doc generation only
Closes #350 
Please note that the test_spectral_irf.py unit test is now reliably failing at runtime, issue #352 has been opened for that.
> address recent flake8 errors

- docs/source/conf.py
- requirements_dev.txt
For details see #390
closes #390
> Adopt to changes in sphinx_copybutton

- glotaran/builtin/models/kinetic_image/kinetic_image_result.py
Added reduced k_matrix to the output object in response to feature request #273 
Steps to be taken:
1. Check with feature request author: is this what is needed?
2. Consider (different) naming
3. Write test cases
4. Review PR
5. Merge into master
> Adds a k_matrix_reduced object to the result object

- glotaran/analysis/matrix_calculation.py
- glotaran/analysis/optimize.py
- glotaran/analysis/residual_calculation.py
- glotaran/analysis/test/mock.py
- glotaran/analysis/test/test_optimization.py
- glotaran/builtin/models/doas/doas_model.py
- glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py
- glotaran/model/model_decorator.py
> Changed 'dependend' to 'dependent'

- glotaran/analysis/optimize.py
- glotaran/analysis/scheme.py
- glotaran/analysis/test/test_scheme.py
cherry picked some changes from the irf_convolution branch
**Testing**
Should pass test
closes #416
> fix apply_weights call prepare_data from optimize_task

- .github/dependabot.yml
- .github/workflows/CI_CD_actions.yml
- Adds dependabot updates for used action versions
- Install `wheel` before dependencies so the dependencies are installed using their wheels
> Improve CI

- .pre-commit-config.yaml
Just so we don't miss any cool syntax sugar 😉
> Change pyupgrade flag from '--py36-plus' to '--py38-plus'

- glotaran/analysis/problem.py
- glotaran/analysis/test/mock.py
- glotaran/analysis/test/test_optimization.py
The dataset scale parameter is now applied also on the dataset.
Closes #471
> Fixed Application of dataset scale.

- glotaran/analysis/optimize.py
- glotaran/analysis/problem.py
- glotaran/analysis/test/test_problem.py
Added optimizer call for the problem class
Refactored problem class to change name of full_clps to just clps
This is only partial work towards fixing issue #478, but this needs to be in prior to further refactoring.
> Small optimize and problem class refactor

- glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py
Fix for glotaran/pyglotaran/#476
Changed axis deque to np.array prior to subtraction with int
**Testing**
All tests are passing
closes #476
> Fix for incompatible types in spectral_relations

- glotaran/analysis/problem.py
- glotaran/analysis/simulation.py
- glotaran/analysis/test/mock.py
- glotaran/analysis/test/test_optimization.py
- glotaran/analysis/test/test_problem.py
- glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py
- glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py
- glotaran/builtin/models/kinetic_spectrum/spectral_relations.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_constraints.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_relations.py
- glotaran/model/decorator.py
- glotaran/parse/test/test_model_parser_kinetic.py
- glotaran/parse/test/test_model_spec_kinetic.yml
Got rid of full_clp_labels
Calculate additional_penalty_function using reduced_clp_labels
**Testing**
All tests are passing
Closes #478
> [WIP] Fix for full_clp_labels None in grouped analysis

- .github/CODEOWNERS
- .github/workflows/sanity.yml
Added CODEOWNERS for clarifying primary code responsibility
Following documentation here:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
> Add CODEOWNERS file to main branch

- glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py
- glotaran/parameter/parameter.py
- glotaran/parameter/parameter_group.py
- glotaran/parameter/test/test_parameter.py
Fixed parameter evaluation in subgroups.
Added parameter sanitation for scientific notation.
Resolves #501
> Various changes in `glotaran.parameter`.

- glotaran/analysis/optimize.py
- glotaran/analysis/problem.py
- glotaran/analysis/scheme.py
- glotaran/analysis/test/models.py
- glotaran/analysis/test/test_grouping.py
- glotaran/analysis/test/test_optimization.py
- glotaran/analysis/test/test_problem.py
- glotaran/analysis/test/test_scheme.py
- glotaran/analysis/test/test_simulation.py
- glotaran/builtin/models/kinetic_image/test/test_kinetic_image_model.py
- glotaran/builtin/models/kinetic_spectrum/test/test_coherent_artifact.py
- glotaran/builtin/models/kinetic_spectrum/test/test_kinetic_spectrum_model.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_constraints.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_irf.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_relations.py
- glotaran/model/decorator.py
- glotaran/model/test/test_model.py
- glotaran/parse/test/test_register.py
Fixes #521 
IMPORTANT
=======
Changed argument and property names of  `Scheme` to comply with glotaran naming conventions.
> Refactored Scheme

- glotaran/analysis/optimize.py
- glotaran/analysis/problem.py
- glotaran/analysis/result.py
- glotaran/model/decorator.py
additional_penalty is a vector with the number of element equal to the number of penalties in the model scheme
Making the additional_penalty available to the Result class for reporting.
Closes #525
> Additional reporting

- docs/source/introduction.rst
- glotaran/analysis/problem.py
- glotaran/analysis/result.py
- glotaran/analysis/scheme.py
- glotaran/analysis/test/test_scheme.py
- glotaran/builtin/models/kinetic_image/test/test_kinetic_image_model.py
- glotaran/builtin/models/kinetic_spectrum/test/test_kinetic_spectrum_model.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py
> Fix typo in non negative least squares

- glotaran/analysis/result.py
- glotaran/analysis/test/test_optimization.py
Fixed code to the point where get_scheme works to return a new scheme object on which optimize can be called.
Closes #539
> Fixed arguments in Result's get_scheme call

- LICENSE
- setup.py
As agreed between @glotaran/pyglotaran_creators on Feb 8th 2021 the LICENSE shall be changed to LGPLv3 in preparation for the v0.3.0 release and going forward.
Closes #545
> Change LICENSE to LGPLv3

- glotaran/cli/commands/optimize.py
- glotaran/cli/commands/util.py
Quick fix to CLI so as to not have a completely broken CLI in v0.3.0
Closes #550
> Hotfix CLI

- .github/workflows/autoupdate-pre-commit-config.yml
Hopefully, this will let @jsnel do his job as maintainer and review PRs created by the github action.
> Fix pre commit autoupdate bot

- docs/source/quickstart.rst
This fixes a typo in the documentation
> Replace model.py -> model.yml

- HISTORY.rst
- glotaran/__init__.py
I bumped the version and added the important changes to the history.
@jsnel Feel free to change what needs changing 😄
> Prepare v0.3.1 release

- glotaran/analysis/problem.py
- glotaran/io/prepare_dataset.py
Cherry picked fix for #574 included in PR #575 for the v0.3 maintenance branch to main.
Closes #574
> Fix excessive memory usage in _create_svd

- .github/workflows/CI_CD_actions.yml
- CONTRIBUTING.rst
- setup.cfg
This is PR is based on #449 and as a preparation for when numba adds python 3.9 compatibility, which should be in [about 3 weeks](https://github.com/numba/numba/issues/6345#issuecomment-721738251)
> Add python 3.9 support

- .zenodo.json
Added config file based on the example generated by zenodo
JSON Export example found at: https://zenodo.org/account/settings/github/repository/glotaran/pyglotaran#
Type: Needs forwardport
Closes #579
> Add a Zenodo config file

- .github/workflows/CI_CD_actions.yml
- CONTRIBUTING.rst
- glotaran/analysis/scheme.py
- glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py
- requirements_dev.txt
- setup.cfg
Various patches for v0.3 maintenance branch.
Fix issues with renaming of SVD related attributes #597 
Fix slowdown in equal area penalty calculation #598 
Profiling before and after shows a >10x speedup:
290s [profile_with_area_check_main.pdf](https://github.com/glotaran/pyglotaran/files/6138107/profile_with_area_check_main.pdf)
23s [profile_no_area_check_main.pdf](https://github.com/glotaran/pyglotaran/files/6138105/profile_no_area_check_main.pdf)
> Maintenance/patches for v0.3.3

- .zenodo.json
- HISTORY.rst
- README.md
- glotaran/__init__.py
- glotaran/analysis/problem.py
- glotaran/builtin/models/kinetic_spectrum/spectral_penalties.py
Forward port v0.3.3 changes and release notes.
Fix issues with renaming of SVD related attributes #597
Fix slowdown in equal area penalty calculation #598
> Maintenance/forward port v0.3.3 changes

- .pre-commit-config.yaml
> ⬆️ UPGRADE: Manual update pre-commit config

- .pre-commit-config.yaml
- glotaran/analysis/problem.py
- glotaran/builtin/io/ascii/wavelength_time_explicit_file.py
- glotaran/builtin/models/kinetic_image/k_matrix.py
- glotaran/builtin/models/kinetic_spectrum/test/test_spectral_penalties.py
- glotaran/parameter/parameter.py
default branch (https://github.com/glotaran/pyglotaran/tree/main)
<details>
<summary>Details: </summary>
<details>
<summary><em>add path</em></summary>
```Shell
/home/runner/work/_actions/technote-space/create-pr-action/v2/node_modules/npm-check-updates/bin
```
</details>
<details>
<summary><em>pip install pre-commit</em></summary>
```Shell
Collecting pre-commit
Downloading pre_commit-2.12.0-py2.py3-none-any.whl (189 kB)
Collecting toml
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting cfgv>=2.0.0
Downloading cfgv-3.2.0-py2.py3-none-any.whl (7.3 kB)
Collecting pyyaml>=5.1
Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
Collecting nodeenv>=0.11.1
Downloading nodeenv-1.6.0-py2.py3-none-any.whl (21 kB)
Collecting virtualenv>=20.0.8
Downloading …
```
> ⬆️ UPGRADE: Autoupdate pre-commit config

- .github/workflows/integration-tests.yml
Adds workflow to run the [pyglotaran-examples](https://github.com/glotaran/pyglotaran-examples).
**Testing**
closes #657
> 🧪 Add integration test workflow which runs the examples

- glotaran/builtin/io/yml/test/test_model_spec_kinetic.yml
- glotaran/builtin/models/kinetic_image/irf.py
- glotaran/builtin/models/kinetic_image/kinetic_decay_megacomplex.py
- glotaran/builtin/models/kinetic_image/kinetic_image_model.py
- glotaran/builtin/models/kinetic_image/kinetic_image_result.py
- glotaran/builtin/models/kinetic_image/test/test_kinetic_image_model.py
- glotaran/builtin/models/kinetic_spectrum/coherent_artifact_megacomplex.py
- glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_result.py
- glotaran/builtin/models/kinetic_spectrum/spectral_irf.py
This PR adds the possibility to model a per wavelength shift of a MultiGussianIrf.
> Add Channel/Wavelength dependend shift paramter to irf.

- glotaran/builtin/models/spectral/__init__.py
- glotaran/builtin/models/spectral/shape.py
- glotaran/builtin/models/spectral/spectral_megacomplex.py
- glotaran/builtin/models/spectral/spectral_model.py
- glotaran/builtin/models/spectral/spectral_result.py
- glotaran/builtin/models/spectral/test/test_spectral_model.py
- setup.cfg
This PR adds a pure spectral model to glotaran.
> Add basic spectral model

- glotaran/builtin/models/kinetic_image/irf.py
Just something we overlooked in the review of #673
**Testing**
> ♻️ Refactor IrfMultiGaussian.calculate to be more pythonic

- glotaran/analysis/optimize.py
- glotaran/analysis/problem.py
- glotaran/analysis/problem_grouped.py
- glotaran/analysis/problem_ungrouped.py
- glotaran/analysis/test/test_grouping.py
- glotaran/analysis/test/test_problem.py
This just an internal refactor, no changes visible for users.
> Refactored Problem class into GroupedProblem and UngroupedProblem

- glotaran/analysis/simulation.py
- glotaran/builtin/models/kinetic_image/k_matrix.py
Just some minimal cleaning up.
**Testing**
> 🧹 Followup cleanup for #686

- .pre-commit-config.yaml
- glotaran/builtin/models/kinetic_spectrum/spectral_matrix.py
- glotaran/cli/commands/explore.py
- glotaran/cli/commands/util.py
- glotaran/model/attribute.py
- glotaran/plugin_system/base_registry.py
Added flake8-comprehensions to pre-commit flake8 step and fixed linting issues.
- flake8 pre-commit uses flake8-comprehensions
closes #698
> 🔧 Use flake8-comprehensions

- .github/workflows/pr_benchmark.yml
This will give us a better overview of the changes between versions.
- PR benchmark workflow runs benchmarks from 0.4.0 onward
> 👌 Changed PR benchmark workflow to run benchmarks from last release

- .github/workflows/integration-tests.yml
Adds more integration tests supported by the `glotaran/pyglotaran-examples@main` gh-action.
- Use all supported integration tests
> 🚇 Add more integration tests

- .github/workflows/pr_benchmark.yml
- benchmark/benchmarks/__init__.py
- benchmark/benchmarks/integration/ex_two_datasets/benchmark.py
- benchmark/benchmarks/unit/analysis/bench_optimize.py
Adds additional benchmarks based on the test in `glotaran/analysis/test/test_optimization.py`
- `asv` benchmarks different paths for `optimize`
> 🧪 Add fine grain optimize benchmark

- .pre-commit-config.yaml
- benchmark/pytest/analysis/test_problem.py
- glotaran/analysis/nnls.py
- glotaran/analysis/optimize.py
- glotaran/analysis/problem.py
- glotaran/analysis/problem_ungrouped.py
- glotaran/analysis/simulation.py
- glotaran/analysis/test/models.py
- glotaran/analysis/test/test_constraints.py
- glotaran/analysis/test/test_optimization.py
- glotaran/analysis/test/test_problem.py
- glotaran/analysis/util.py
- glotaran/analysis/variable_projection.py
- glotaran/builtin/megacomplexes/baseline/baseline_megacomplex.py
- glotaran/builtin/megacomplexes/coherent_artifact/coherent_artifact_megacomplex.py
- glotaran/builtin/megacomplexes/decay/decay_megacomplex.py
- glotaran/builtin/megacomplexes/decay/util.py
- glotaran/builtin/megacomplexes/spectral/spectral_megacomplex.py
- glotaran/model/dataset_model.py
- glotaran/model/interval_property.py
- glotaran/model/megacomplex.py
- glotaran/model/model.py
- glotaran/model/test/test_model.py
- glotaran/project/scheme.py
- glotaran/test/test_spectral_decay.py
- glotaran/test/test_spectral_decay_full_model.py
- glotaran/test/test_spectral_penalties.py
This PR adds the ability to optimize full models to glotaran. 
- Full models can be fitted
- ~~Only non index dependent models are supported for now (might change till finishof this PR)~~
- No relations and constraints are supported on either the global and model matrix
- Clp penalties are not supported
closes #750
> Feature: Full Models

- changelog.md
I added the changes on the `maintenance/v0.4.1` branch to the changelog.
> 🚀 Prepare release 0.4.1

- .pre-commit-config.yaml
- glotaran/analysis/test/test_constraints.py
- glotaran/analysis/test/test_optimization.py
- glotaran/analysis/test/test_penalties.py
- glotaran/analysis/test/test_problem.py
- glotaran/analysis/test/test_relations.py
- glotaran/builtin/io/ascii/wavelength_time_explicit_file.py
- glotaran/builtin/io/yml/test/test_model_parser.py
- glotaran/builtin/megacomplexes/damped_oscillation/test/test_doas_model.py
- glotaran/builtin/megacomplexes/spectral/test/test_spectral_model.py
- glotaran/model/test/test_model.py
- glotaran/test/test_spectral_decay.py
- glotaran/test/test_spectral_decay_full_model.py
- glotaran/test/test_spectral_penalties.py
- tox.ini
Added flake8-print to the flake8 hook and allowed printing in test_ files by default.
Ref: https://github.com/glotaran/pyglotaran/pull/763#issuecomment-894823991
- Disallow print if not specifically allowed
> 🔧 Use flake8-print in pre-commit

- .github/ISSUE_TEMPLATE/refactor.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/bug_fix_PR.md
- .github/PULL_REQUEST_TEMPLATE/docs_PR.md
- .github/PULL_REQUEST_TEMPLATE/feature_PR.md
- .github/PULL_REQUEST_TEMPLATE/refactor_PR.md
- CONTRIBUTING.rst
- changelog.md
- glotaran/__init__.py
Reset the version back to a dev version and change contributing guide instructing contributors to add their changes to the change log.
- ⬆️ Changed version to 0.6.0.dev0
- 📚 Added 0.6.0 boilerplate section in changelog
- 👌🚧 Added 'Added changes to changelog' checkbox to PR templates
- 📚 Updated contributing guide with instructions to add changes to changelog
Links to the changed sections
- [PR guide](https://pyglotaran--922.org.readthedocs.build/en/922/contributing.html#get-started) Step `9.` added
> 🚧 Reset version to development version

- requirements_dev.txt
This is just a combination PR of:
- #943  
- #940
- #941
- #934 
closes #943, #940, #941, #934
> ⬆️ Combined dependabot updates

- changelog.md
Just adding #860 to the changelog which we forgot in the actual PR.
- 🚧📚 Added changes of PR 860 to changelog
> 🚧📚 Add changes of PR 860 to changelog

- .pre-commit-config.yaml
- glotaran/utils/sanitize.py
Updates pre-commit and "fixes" issue with mypy.
- ⬆️🔧 Updated pre-commit
- 🩹 'Fixed' issue with mypy
closes #726
> ⬆️🔧 Update pre-commit

- requirements_dev.txt
Combined updates from dependabot PRs:
-  Bump numba from 0.55.0 to 0.55.1 #980 
-  Bump pandas from 1.3.5 to 1.4.0 #971 
-  Bump pandas from 1.3.5 to 1.4.0
-  Bump numba from 0.55.0 to 0.55.1
> 🚧⬆️ Combined updates

- glotaran/builtin/megacomplexes/coherent_artifact/coherent_artifact_megacomplex.py
- glotaran/builtin/megacomplexes/decay/test/test_decay_megacomplex.py
- glotaran/builtin/megacomplexes/decay/util.py
The irfs shifted centers are stored in the result now.
closes #987
> Added irf shift to result dataset.

- changelog.md
- glotaran/builtin/megacomplexes/coherent_artifact/coherent_artifact_megacomplex.py
- glotaran/builtin/megacomplexes/coherent_artifact/test/test_coherent_artifact.py
The irf shift now gets correctly applied to the coherent artifact. Also the index dependency of the coherent artifact has been fixed.
closes #991
> Apply irf shift in coherent artifact.

- glotaran/builtin/megacomplexes/decay/util.py
While working on some plotting code and validating it with case studies that aren't yet in the examples repository (more code paths). I found that `finalize_data` for decay megacomplexes (introduced in #860)
https://github.com/glotaran/pyglotaran/blob/9e3e36a2033c988a59cbf1be15438d911f141657/glotaran/builtin/megacomplexes/decay/util.py#L78
crashes fur full models
```python
result = optimize(scheme)
File "/mnt/d/git/pyglotaran/glotaran/analysis/optimize.py", line 76, in optimize
return _create_result(
File "/mnt/d/git/pyglotaran/glotaran/analysis/optimize.py", line 137, in _create_result
group.create_result_data(parameter_history, success=success, add_svd=scheme.add_svd)
File "/mnt/d/git/pyglotaran/glotaran/analysis/optimization_group.py", line 331, in create_result_data …
```
> 🩹 Fix missing loop in none full decay model finalize_data

- .github/workflows/CI_CD_actions.yml
- .github/workflows/integration-tests.yml
- changelog.md
Same as #978 but for sourcery AI branches.
- [🚇 Ignore push events on the CI for sourcery branches](https://github.com/glotaran/pyglotaran/commit/dfce81ba805b3acbad8166127c40cec31835a509)
> 🚇👌 Exclude sourcery AI push CI runs

- .github/workflows/autoupdate-pre-commit-config.yml
- requirements_dev.txt
Combines PRs:
- #1026
- #1025 
- #1009 
- [Bump rich from 11.2.0 to 12.0.1](https://github.com/glotaran/pyglotaran/commit/feee3675503d5c185c9c51e3dbc3d6a7f10e9f7c)
- [Bump actions/cache from 2 to 3](https://github.com/glotaran/pyglotaran/commit/491bcd87125bd0877ed916a08c1b6e8737a01434)
- [Bump xarray from 0.21.1 to 2022.3.0](https://github.com/glotaran/pyglotaran/commit/8a22e808cf562a0a72c63673bc8a13fba27798b5)
closes #1026
closes #1025
closes #1009
> ⬆️ Combined updates

- .pre-commit-config.yaml
- glotaran/analysis/optimization_group.py
- glotaran/analysis/optimize.py
- glotaran/builtin/megacomplexes/coherent_artifact/coherent_artifact_megacomplex.py
- glotaran/builtin/megacomplexes/damped_oscillation/damped_oscillation_megacomplex.py
- glotaran/builtin/megacomplexes/decay/irf.py
- glotaran/parameter/parameter.py
- glotaran/parameter/test/test_parameter.py
The CI is failing due to the click 8.1.0 release see [black issue 2964](https://github.com/psf/black/issues/2964)
This change is needed for other PRs to go on and the CI to pass, e.g. #1022 
- [⬆️ Update pre-commit config](https://github.com/glotaran/pyglotaran/commit/a849cf3c95602b9fa8c09978b7f24fa900a2645e)
> ⬆️ Update pre-commit config

- .github/test_result_consistency.py
- changelog.md
- glotaran/analysis/optimize.py
- glotaran/builtin/megacomplexes/decay/decay_megacomplex.py
- glotaran/builtin/megacomplexes/decay/decay_parallel_megacomplex.py
- glotaran/builtin/megacomplexes/decay/decay_sequential_megacomplex.py
- glotaran/builtin/megacomplexes/decay/k_matrix.py
- glotaran/builtin/megacomplexes/decay/test/test_decay_megacomplex.py
- glotaran/builtin/megacomplexes/decay/test/test_spectral_irf.py
- glotaran/builtin/megacomplexes/decay/util.py
- lifetime and rate coordinate now get suffixes 
- suffixes are now always added for megacomplex specific data like DAS
- initial concentration has been added to result data
- a guard for missing data has been added
closes #1021
> 👌🧹 Add suffix to rate and lifetime and guard for missing datasets

- .sourcery.yaml
- glotaran/plugin_system/megacomplex_registration.py
Salvaged changes from #1049 as a preparation for Sourcery AI refactor of the main branch.
Ref: https://github.com/glotaran/pyglotaran/pull/1049#issuecomment-1093146679
- [🔧Improve sourcery ai config to fit our needs](https://github.com/glotaran/pyglotaran/commit/e05082495e8d39b85f1ccd7b0b9472596a2ff808)
- [👌 Improve typing for later sourcery ai refactoring](https://github.com/glotaran/pyglotaran/commit/9d1378de7187839056ee31cdd7ba9a043d85961d)
> 🔧 Adjust sourcery config

- changelog.md
- glotaran/builtin/megacomplexes/decay/util.py
small bug fix related to normalization of datasets
- Changed normalization of concentration matrix if dataset_model.irf.normalize is true.
closes #1157
> fix bug in irf normalization (added an "s" after irfscale)

- benchmark/pytest/analysis/test_optimization_group.py
An issue that came to @joernweissenborn mind in the train. 😅
- [👌 Add index dependent benchmark test matrix](https://github.com/glotaran/pyglotaran/commit/ffc18028662ecade791330734710d011774cd1a1)
> 👌 Add index dependent benchmark test matrix

- .pre-commit-config.yaml
- benchmark/pytest/analysis/test_optimization_group.py
- glotaran/builtin/megacomplexes/baseline/baseline_megacomplex.py
- glotaran/builtin/megacomplexes/clp_guide/clp_guide_megacomplex.py
- glotaran/builtin/megacomplexes/coherent_artifact/coherent_artifact_megacomplex.py
- glotaran/builtin/megacomplexes/damped_oscillation/damped_oscillation_megacomplex.py
- glotaran/builtin/megacomplexes/decay/decay_matrix_gaussian_irf.py
- glotaran/builtin/megacomplexes/decay/decay_megacomplex.py
- glotaran/builtin/megacomplexes/decay/decay_parallel_megacomplex.py
- glotaran/builtin/megacomplexes/decay/decay_sequential_megacomplex.py
- glotaran/builtin/megacomplexes/decay/util.py
- glotaran/builtin/megacomplexes/spectral/spectral_megacomplex.py
- glotaran/model/megacomplex.py
- glotaran/model/model.py
- glotaran/optimization/data_provider.py
- glotaran/optimization/estimation_provider.py
- glotaran/optimization/matrix_provider.py
- glotaran/optimization/nnls.py
- glotaran/optimization/optimization_group.py
- glotaran/optimization/optimizer.py
- glotaran/optimization/test/models.py
- glotaran/optimization/variable_projection.py
- glotaran/parameter/parameter.py
- glotaran/simulation/simulation.py
- glotaran/typing/types.py
- tox.ini
This PR fixes a [typing issue](https://github.com/glotaran/pyglotaran/actions/runs/3974638882/jobs/6814017857) that emerged after merging [a pre-commit PR](https://github.com/glotaran/pyglotaran/pull/1215) this was most likely due to cache invalidation issues.
One of the main problems was `np.typing.ArrayLike` which is a union of all types that can be converted to an array and not a Protocol like type that defines which attributes and methods need to be defined like the name would suggest.
To reproduce it you need to clean your pre-commit cache (`pre-commit clean`) and run `pre-commit run --all` on the current main
- [🩹 Fix typing problems](https://github.com/glotaran/pyglotaran/commit/ab5992b357da0647857490d18c7c55d244128b98)
> 🩹 Fix typing problems

- changelog.md
- glotaran/plugin_system/base_registry.py
- glotaran/plugin_system/data_io_registration.py
- glotaran/plugin_system/project_io_registration.py
- glotaran/plugin_system/test/test_base_registry.py
- glotaran/plugin_system/test/test_data_io_registration.py
- glotaran/plugin_system/test/test_io_plugin_utils.py
- glotaran/plugin_system/test/test_megacomplex_registration.py
- glotaran/plugin_system/test/test_project_io_registration.py
- glotaran/project/project_data_registry.py
- glotaran/project/project_model_registry.py
- glotaran/project/project_parameter_registry.py
- glotaran/project/project_registry.py
- glotaran/project/test/test_project.py
- glotaran/testing/plugin_system.py
This change allows the project API to leverage the full plugin system to detect and read
- Models
- Parameters
- Data
- [♻️ Changed plugin_system implementation check functions to generators](https://github.com/glotaran/pyglotaran/commit/810b40b1caae331888f546e1e4d16c912c1f9c6c)
- [♻️ Refactored test_base_registry and added test case for all methods implemented](https://github.com/glotaran/pyglotaran/commit/90e40f0069b218444281f26b92496d20398a3ed4)
- [✨ Added supported_file_extensions function to base_registry](https://github.com/glotaran/pyglotaran/commit/e622e6bbc57d1284488096736aee1f9299db1b91)
- [✨ Added supported_file_extensions function for project and data io](https://github.com/glotaran/pyglotaran/commit/92b98be70a1f69affd4bc42454f0de8e03be5c38)
- ♻️ Refactored plugin registry …
> ✨ Integrate plugin system into Project

- README.md
Just some cleanup after LGTM got inegrated into github as CodeQL and we switched to the new workflow in #1197 .
- [🧹 Replace LGTM badge with CodeQL badge](https://github.com/glotaran/pyglotaran/commit/5fb8d92c7d3276f676e32205d5365dd2fe8202f8)
closes #1236
> 🧹 Replace LGTM badge with CodeQL badge

- glotaran/optimization/penalty.py
A equal area constraint can be a bit heavy without it ^^
> Take into account the weight factor in clp_penalties

- glotaran/project/scheme.py
Adds standard errors to the optimized parameters
> Add call to calculate_parameter_errors before returning Result

- .github/workflows/full_benchmark.yml
- .github/workflows/pr_benchmark_reaction.yml
- requirements_dev.txt
Combined bot updates
- [Bump ruamel-yaml from 0.17.35 to 0.18.5](https://github.com/glotaran/pyglotaran/commit/3e38dbfcca67b18b86b3ec82045e74308ffd1d6d)
- [Bump pandas from 2.1.1 to 2.1.2](https://github.com/glotaran/pyglotaran/commit/a3bf12b86833b1a6a1c981c7a43c91ce319e4862)
- [Bump netcdf4 from 1.6.4 to 1.6.5](https://github.com/glotaran/pyglotaran/commit/d93be53569342ef788c2787f99afa5283e475a63)
- [Bump xarray from 2023.9.0 to 2023.10.1](https://github.com/glotaran/pyglotaran/commit/6e6e9f662a3e6356aebbb92d1e7ef36594b0eed1)
- [Bump scipy from 1.11.2 to 1.11.3](https://github.com/glotaran/pyglotaran/commit/52af341559c6ea510e9a69bbd409c9780e64050b)
- [Bump ad-m/github-push-action from 0.6.0 to 0.8.0](https://github.com/glotaran/pyglotaran/commit/a3d9125b33ac2cfab3accacebf50e31cf3c74c19) …
> ⬆️ Combi updates

- .github/workflows/CI_CD_actions.yml
- .github/workflows/autoupdate-pre-commit-config.yml
- .github/workflows/codeql.yml
- .github/workflows/doxygen.yml
- .github/workflows/full_benchmark.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr_benchmark.yml
Combined update of github actions
- [Bump actions/cache from 3 to 4](https://github.com/glotaran/pyglotaran/commit/b439d232a82c641ab9d2505e2d05c4c6118bc13e)
- [Bump codecov/codecov-action from 3 to 4](https://github.com/glotaran/pyglotaran/commit/01e67573a86736b0fbdf412504f2ba52115e0ffc)
- [Bump github/codeql-action from 2 to 3](https://github.com/glotaran/pyglotaran/commit/84aede05cec1f42e7f3a83abe0046ac5f55c2716)
- [Bump actions/upload-artifact from 3 to 4](https://github.com/glotaran/pyglotaran/commit/5922f81350ea55a4c5d039465ae2de93d1b94d96)
- [Bump actions/download-artifact from 3 to 4](https://github.com/glotaran/pyglotaran/commit/c0529a78a70261e179c86de83506596ba98346d3)
- [🩹 Adapt to changes in artifact actions](https://github.com/glotaran/pyglotaran/commit/03b0c56e8d359236c0090052 …
> ⬆️ Combined github actions updates

- .github/workflows/CI_CD_actions.yml
- pyproject.toml
- requirements_pinned.txt
This is a forward port of #1437 
- [✨ Add python 3.12 support](https://github.com/glotaran/pyglotaran/commit/b3edcf68dfd19eedbff36399d5338ee927943da3)
- [⬆️ Updaze pinned dependencies](https://github.com/glotaran/pyglotaran/commit/32765e9ae0ca8f27c7f79bc6cdb9fcadc3ed72f8)
> ✨ Add official Python 3.12 support

- glotaran/optimization/data.py
- glotaran/optimization/matrix.py
- tests/optimization/test_matrix.py
- Remove scaling of (raw) data
- Add scaling to optimization matrix
[closes #1463](https://github.com/glotaran/pyglotaran/issues/1463)
> 🩹 Fix scaling for linked dataset case

- changelog.md
- docs/source/conf.py
- glotaran/__init__.py
- setup.cfg
This PR prepares the code base for the 0.7.3 release.
- [🚧 Bump version from 0.7.2 to 0.7.3](https://github.com/glotaran/pyglotaran/commit/a767d9096dd5951d32bf52b04990dca693688cfa)
- [📚🩹 Add release date of 0.7.0 to changelog](https://github.com/glotaran/pyglotaran/commit/3d663bdef57a9717ff19a6abd7dd8bfa7e6610ad)
- [📚🩹 Add PR nr for ASV benchmark drop](https://github.com/glotaran/pyglotaran/commit/15fe56aff6cc83d0dd825d21f8f3e96a4ade09f3)
> 🚀 Prepare 0.7.3 release
